---
Tutorial 1
==========


1.  Calculate the following accumulation:

    1.  Accumulate \$5,000 for 4 years at 7.5% per annum effective.

    2.  Accumulate \$800 for 2.7 years at 3% per quarter-year effective.

    3.  Accumulate \$10,000 for 27 months at 4.25% per half-year
        effective.

2.  Calculate the present values on 1 January 2015 of the following
    payments at the given rates of interest:

    1.  \$1,000 on 1 January 2016, at 7.5% per annum effective.

    2.  \$100 on 1 October 2016, at 3% per quarter-year effective.

    3.  \$10,000 on 1 April 2016, at 4.25% per half-year effective.

3.  1.  If the effective rate of interest is 4% per annum, calculate the
        effective rate of interest per month?

    2.  If the effective rate of interest is 6.5% per half-year,
        calculate the effective rate of interest per quarter-year?

4.  The effective rate of interest per annum was 4% during 2015, 5%
    during 2016 and 6% thereafter.

    1.  Calculate the accumulation of \$500 from 1 January 2015 to 1
        January 2018.

    2.  Calculate the accumulation of \$2000 from 1 April 2015 to 1
        October 2017.

    3.  Calculate the accumulation factor from 1 January 2015 to 1
        January 2018.

5.  You deposit \$ 3000 to an account that earn 2.5% compounded
    annually. How much will you have in three years?

6.  A person borrows a sum of \$5,000 and agrees to pay this back at the
    end of 1 year with interest calculated at an effective rate of 10%
    per annum. Calculate the amount to be repaid for the loan.

7.  You want to have \$1000 in 2 years and \$2000 in 4 years. How much
    should you deposit now into an account earning the effective rate of
    5.75% semiannually?

8.  Katy deposits 100 into a saving account which pays interest at $i$
    **per quarter** effective.

    At the same time, Taylor deposits 500 into a different saving
    account which pays a simple interest at an annual rate of $i$.

    During the last 3 months of the 4th year, they both earn the same
    amount of interest. Calculate $i$.

9.  An ordinary annuity is a series of equal payments made at the end of
    consecutive periods over a fixed length of time. Draw a timeline for
    the following annuity having cashflow of 1 unit at the end of each
    of the next n time units.

10. Draw a timeline to illustrate this insurance benefit: Whole Life
    Insurance - payable immediately on death - has following conditions:

    -   death benefit (sum insured) of 1

    -   payable immediately on the death

    -   of an individual currently aged x

    -   for death occurring any time in the future.

11. (Excel) It is a good exercise to check whether the Excel worksheet
    you have developed so far for calculating the present value and
    future value can be applied to the questions in this Tutorial. What
    would you do to improve the Excel worksheet that can be applied to a
    more general scenario?

Tutorial 2
==========

1.  Starting at 1 January 2015, the effective rate of interest per annum
    was 3% per quarter-year for 9 months, 4% per half-year for 15 months
    and and 2% per month thereafter.

    1.  Calculate the accumulation factor from 1 January 2015 to 1
        January 2018.

    2.  Calculate the accumulation of \$5,000 from 1 July 2015 to 1
        October 2017.

    3.  Calculate the accumulation of \$100 from 1 March 2016 to 1
        August 2018.

    4.  Calculate the present value at 1 January 2015 of \$ 25,000
        receivable on 1 July 2016.

    5.  Calculate the present value at 1 April 2015 of \$ 8,000
        receivable on 1 October 2017.

    6.  Calculate the discount factor from 1 July 2015 to 1
        October 2016.

2.  The effective rate of interest is 7.25% per time unit. Cashflows are
    shown in the following time line.

    1.  Calculate the accumulation at time time t = 4 units of these
        cashflows.

    2.  Calculate the accumulation at time time t = 8 units of these
        cashflows.

    3.  Calculate the present value at time time t = 0 units of these
        cashflows.

 
```{tikz, tikz-exam1, fig.ext = 'png', cache=TRUE, echo = FALSE,fig.align="center"}
\usetikzlibrary{snakes}
\tikzset{every picture/.style={line width=0.75pt}} %set default line width to 0.75pt        

\begin{tikzpicture}[snake=zigzag, line before snake = 5mm, line after snake = 5mm, scale=2.5]
    % draw horizontal line   
    \draw[->]  (0,0) -- (5,0);
%    %\draw[snake] (2,0) -- (4,0);
%    \draw[] (2,0) -- (4,0);
%    \draw (4,0) -- (5,0);
%    \draw[->] (0,0) -- (7,0);

    % draw vertical lines
    \foreach \x in {0,1,2,3,4}
      \draw (\x cm,2pt) -- (\x cm,-2pt);

    % draw nodes
    \draw (0,0) node[below=5pt] {$ t= 0 $} node[above=5pt] {$ \Big \downarrow $};
    \draw (0,0) node[above=25pt] {$  +100  $};

    
    \draw (1,0) node[below=5pt] {$ 1 $} node[above=3pt] {$  $};
    \draw (1,0) node[below=15pt] {$  \Big \downarrow $};
    \draw (1,0) node[below=35pt] {$  -30 $};
    
    \draw (2,0) node[below=5pt] {$ 2 $} node[above=3pt] {$  $};
    \draw (2,0) node[below=15pt] {$  \Big \downarrow $};
    \draw (2,0) node[below=35pt] {$  -30 $}; 
   
    \draw (3,0) node[below=5pt] {$ 3 $} node[above=3pt] {$ \Big \downarrow $};
    \draw (3,0) node[above=25pt] {$  +100  $};
    
    \draw (4,0) node[below=5pt] {$ 4 $} node[above=3pt] {$  $};
    \draw (4,0) node[below=15pt] {$  \Big \downarrow $};
    \draw (4,0) node[below=35pt] {$  -30 $}; 

    \draw (5.4,0) node[] { time units } node[above=3pt] {$  $};

\end{tikzpicture}
```    


3.  The effective rate of interest is 6% per time unit. Cashflows are
    shown in the following time line.

    1.  Calculate the accumulation at time time t = 5 units of these
        cashflows.

    2.  Calculate the value at time time t = 2 units of these cashflows.

    3.  Calculate the present value at time time t = 0 units of these
        cashflows.

```{tikz, tikz-exam2, fig.ext = 'png', cache=TRUE, echo = FALSE, fig.align="center"}
\usetikzlibrary{snakes}
\tikzset{every picture/.style={line width=0.75pt}} %set default line width to 0.75pt   

 \begin{tikzpicture}[snake=zigzag, line before snake = 5mm, line after snake = 5mm, scale=2.5]
    % draw horizontal line   
    \draw[->]  (0,0) -- (5,0);
%    %\draw[snake] (2,0) -- (4,0);
%    \draw[] (2,0) -- (4,0);
%    \draw (4,0) -- (5,0);
%    \draw[->] (0,0) -- (7,0);

    % draw vertical lines
    \foreach \x in {0,1.25,2.75,3.5,4}
      \draw (\x cm,2pt) -- (\x cm,-2pt);

    % draw nodes
    \draw (0,0) node[below=5pt] {$ t= 0 $} node[above=5pt] {$ \Big \downarrow $};
    \draw (0,0) node[above=25pt] {$  +5,000  $};

    
    \draw (1.25,0) node[below=5pt] {$ 1.25 $} node[above=3pt] {$  $};
    \draw (1.25,0) node[below=15pt] {$  \Big \downarrow $};
    \draw (1.25,0) node[below=35pt] {$  -2,000 $};
    
    \draw (2.75,0) node[below=5pt] {$ 2.75 $} node[above=3pt] {$  $};
    \draw (2.75,0) node[below=15pt] {$  \Big \downarrow $};
    \draw (2.75,0) node[below=35pt] {$  -1,000 $}; 
   
    \draw (3.5,0) node[below=5pt] {$ 3.5 $} node[above=3pt] {$ \Big \downarrow $};
    \draw (3.5,0) node[above=25pt] {$  +4,000  $};
    
    \draw (4,0) node[below=5pt] {$ 4 $} node[above=3pt] {$  $};
    \draw (4,0) node[below=15pt] {$  \Big \downarrow $};
    \draw (4,0) node[below=35pt] {$  -500 $}; 

    \draw (5.4,0) node[] { time units } node[above=3pt] {$  $};

  \end{tikzpicture}
```

4.  The effective rate of interest per annum was 4% during 2015, 3% per
    half-year until 1 October 2017 and 1.5% per month thereafter.
    Cashflows are shown in the following time line.

    1.  Calculate the accumulation on 1/1/2019 of these cashflows.

    2.  Calculate the present value on 1/1/2015 of these cashflows.

    3.  Calculate the value at time time 1/7/2017 of these cashflows.



```{tikz, tikz-exam3, fig.ext = 'png', cache=TRUE, echo = FALSE, fig.align="center"}
\usetikzlibrary{snakes}
\tikzset{every picture/.style={line width=0.75pt}} %set default line width to 0.75pt   

 \begin{tikzpicture}[snake=zigzag, line before snake = 5mm, line after snake = 5mm, scale=2.5]
    % draw horizontal line   
    \draw[->]  (0,0) -- (5,0);
%    %\draw[snake] (2,0) -- (4,0);
%    \draw[] (2,0) -- (4,0);
%    \draw (4,0) -- (5,0);
%    \draw[->] (0,0) -- (7,0);

    % draw vertical lines
    \foreach \x in {0,1.25,2.75,3.5,4}
      \draw (\x cm,2pt) -- (\x cm,-2pt);

    % draw nodes
    \draw (0,0) node[below=5pt] {$ t= 0 $} node[above=5pt] {$ \Big \downarrow $};
    \draw (0,0) node[above=25pt] {$  +5,000  $};

    
    \draw (1.25,0) node[below=5pt] {$ 1.25 $} node[above=3pt] {$  $};
    \draw (1.25,0) node[below=15pt] {$  \Big \downarrow $};
    \draw (1.25,0) node[below=35pt] {$  -2,000 $};
    
    \draw (2.75,0) node[below=5pt] {$ 2.75 $} node[above=3pt] {$  $};
    \draw (2.75,0) node[below=15pt] {$  \Big \downarrow $};
    \draw (2.75,0) node[below=35pt] {$  -1,000 $}; 
   
    \draw (3.5,0) node[below=5pt] {$ 3.5 $} node[above=3pt] {$ \Big \downarrow $};
    \draw (3.5,0) node[above=25pt] {$  +4,000  $};
    
    \draw (4,0) node[below=5pt] {$ 4 $} node[above=3pt] {$  $};
    \draw (4,0) node[below=15pt] {$  \Big \downarrow $};
    \draw (4,0) node[below=35pt] {$  -500 $}; 

    \draw (5.4,0) node[] { time units } node[above=3pt] {$  $};

  \end{tikzpicture}
```




5.  (Excel) It is a good exercise to check whether the Excel worksheet
    you have developed so far for calculating the present value and
    future value can be applied to the questions in this Tutorial. What
    would you do to improve the Excel worksheet for a more general
    scenario?

Tutorial 3
==========

1.  Calculate the present value now of an annuity payable monthly in
    advance. The annual amount of the annuity will be \$ 2,400 for the
    first 10 years and \$ 3,600 for the next 15 years, after which
    payment will cease. Assume that the effective rate of interest is 2%
    per annum.

2.  Assume that the effective rate of interest will be 3% for 5 years
    from now, 4% for the next 5 years and 5% thereafter. Calculate the
    following values:

    1.  The present value of an annuity of \$ 1,000 per annum, payable
        in arrear for 15 years.

    2.  The present value of an annuity due of \$ 500 per annum, payable
        at the beginning of the year for 20 years.

    3.  The accumulation value of an increasing annuity payable yearly
        in arrear for 30 years. The first annual payment is \$ 100, and
        payments will be increase by \$ 100 each year.

    4.  The accumulation value of an increasing annuity payable yearly
        in advance for 18 years. The first annual payment is \$ 1,000,
        and payments will be increase by 2% each year (compound).

    5.  The present value of an annuity of \$ 200, payable in arrear for
        10 years and deferred for 3 years.

3.  You borrow \$ 240,000 from a bank to be repaid by the end of 5
    years. Assume that the interest rate is 4% per annum. Consider the
    following four possible options for the loan to be repaid.

    1.  Calculate the amount of the repayments to repay if you choose to
        repay the loan as late as possible.

    2.  You may choose to repay interest only during the 5 years term of
        loan and repay the capital at the end of the term. Calculate
        interest to be repaid and draw the timeline to illustrate the
        cashflows for the repayment of the loan.

    3.  Calculate the amount X of level instalments to repay the loan
        which will be paid at the end of each year for 5 years and draw
        the timeline to illustrate the cashflows for the repayment of
        the loan.

    4.  Calculate the amount Y of level instalments to repay the loan
        which will be paid at the end of each month for 5 years and draw
        the timeline to illustrate the cashflows for the repayment of
        the loan. **Instalment** is a sum of money due as one of several
        equal payments for something, spread over an agreed period of
        time.

4.  A person now age 30 has received a pension from a company. When he
    retires at age 60, he will be paid on each birthday from the 60 to
    the 85th inclusive. The first annual payment will be half of his
    salary when he retires, and payments will then increase by 2%
    compounding each year. Currently, he receive a salary of \$ 20,000
    and will increase by 3% each year compounding in line with
    inflation. Assume that the effective rate of interest will be 4% for
    the next 20 years and 5% thereafter. Calculate the present value now
    of this pension.

5.  (Excel) Use Excel worksheet you have developed so far to calculate
    the results from the questions in this Tutorial.

# Solutions to Tutorial 1

1. The solutions to each question are as follows:
    
    1. $5000 (1.075)^4 = 6677.345703$ 
    2. Let $i\%$ be the annual rate effective equivalent to $3\%$ per quarter-effective, $i = (1.03)^4 - 1$. 
    Hence, the accumulation is
    $$800(1+i)^{2.7} = 800(1.03)^{4\times2.7} = 1100.859802.$$
    3. Let $j\%$ be the monthly rate effective equivalent to $4.25\%$ per half-year effective, $j = (1.0425)^{2/12} - 1$. 
    Hence, the accumulation is
    $$10000(1.0425)^{(2/12)\times27} = 12059.86056.$$

2. The solutions to each question are as follows:
      1. $\frac{1000}{1.075} = 930.232558$.
      2. $\frac{100}{(1.03)^7} = 81.309151$.
      3. Let $j\%$ be the quarterly rate effective equivalent to         $4.25\%$ per half-year effective, $j = (1.0425)^{2/4} - 1$. 
      Hence, the present value is
      $$10000\times (1+j)^{-5} = 10000(1.0425)^{-(5/2)} = 9011.764643.$$

3. The solutions to each question are as follows:
      
      1. 0.3274%
      2. 3.1988%

4. The solutions to each question are as follows:
      
      1. 500(1.04)(1.05)(1.06) =578.76
      2. $2000(1.04)^{3/4}(1.05)(1.06)^{3/4} =2259.299$
      3. (1.04)(1.05)(1.06) = 1.15752
      
5. The account balance in 3 years is $3000(1.025)^{3} = 3230.67$.

6. The amount to be repaid for the loan is 5000(1.1) = 5500.

7. Let $X$ be the amount to be deposited now. 
      $$X = \frac{1000}{(1.0575)^4} + \frac{2000}{(1.0575)^8} = 2078.36. $$
      
8. At time 3.75 years, Katy has a balance of $100(1+i)^{15}$. The interest on this balance over the next 3 months is  $100(1+i)^{15}\cdot i$.
Taylor earns simple interest on the original amount which is equal to $500i\cdot\frac{3}{12}$. Therefore, we solve for $i$ from the following equation:
$$ 100(1+i)^{15}\cdot i = 500i\cdot\frac{3}{12},$$ which gives $i = 0.014987.$
  
  
9. The timeline for the following annuity having cashflow of 1 unit at the end of each of the next $n$ time units is given in the figure below:
```{tikz, tikz-sol1, fig.ext = 'png', cache=TRUE, echo = FALSE, fig.align="center"}

\tikzset{every picture/.style={line width=0.75pt}} %set default line width to 0.75pt        

\begin{tikzpicture}[x=0.75pt,y=0.75pt,yscale=-1,xscale=1]
%uncomment if require: \path (0,279); %set diagram left start at 0, and has height of 279

%Straight Lines [id:da8691686097400964] 
\draw    (44.5,111) -- (617.5,110) ;
\draw [shift={(619.5,110)}, rotate = 539.9] [color={rgb, 255:red, 0; green, 0; blue, 0 }  ][line width=0.75]    (10.93,-3.29) .. controls (6.95,-1.4) and (3.31,-0.3) .. (0,0) .. controls (3.31,0.3) and (6.95,1.4) .. (10.93,3.29)   ;
%Straight Lines [id:da597257855042824] 
\draw    (60,106) -- (60,117) ;
%Straight Lines [id:da9474951160801843] 
\draw    (181,106) -- (181,117) ;
%Straight Lines [id:da6185331554915787] 
\draw    (301,105) -- (301,116) ;
%Straight Lines [id:da5682405407635602] 
\draw    (570,106) -- (570,117) ;
%Straight Lines [id:da5881588816774714] 
\draw    (301,69) -- (300.53,98) ;
\draw [shift={(300.5,100)}, rotate = 270.92] [color={rgb, 255:red, 0; green, 0; blue, 0 }  ][line width=0.75]    (10.93,-3.29) .. controls (6.95,-1.4) and (3.31,-0.3) .. (0,0) .. controls (3.31,0.3) and (6.95,1.4) .. (10.93,3.29)   ;
%Straight Lines [id:da1927000421177052] 
\draw    (181,69) -- (180.53,98) ;
\draw [shift={(180.5,100)}, rotate = 270.92] [color={rgb, 255:red, 0; green, 0; blue, 0 }  ][line width=0.75]    (10.93,-3.29) .. controls (6.95,-1.4) and (3.31,-0.3) .. (0,0) .. controls (3.31,0.3) and (6.95,1.4) .. (10.93,3.29)   ;
%Straight Lines [id:da43730719784498717] 
\draw    (420,105) -- (420,116) ;
%Straight Lines [id:da5347119577328068] 
\draw    (421,69) -- (420.53,98) ;
\draw [shift={(420.5,100)}, rotate = 270.92] [color={rgb, 255:red, 0; green, 0; blue, 0 }  ][line width=0.75]    (10.93,-3.29) .. controls (6.95,-1.4) and (3.31,-0.3) .. (0,0) .. controls (3.31,0.3) and (6.95,1.4) .. (10.93,3.29)   ;
%Straight Lines [id:da21105992529208994] 
\draw    (571,69) -- (570.53,98) ;
\draw [shift={(570.5,100)}, rotate = 270.92] [color={rgb, 255:red, 0; green, 0; blue, 0 }  ][line width=0.75]    (10.93,-3.29) .. controls (6.95,-1.4) and (3.31,-0.3) .. (0,0) .. controls (3.31,0.3) and (6.95,1.4) .. (10.93,3.29)   ;

% Text Node
\draw (61,131.5) node   [align=left] {$\displaystyle 0$};
% Text Node
\draw (180,132.5) node   [align=left] {$\displaystyle 1$};
% Text Node
\draw (302,131.5) node   [align=left] {$\displaystyle 2$};
% Text Node
\draw (571,129.5) node   [align=left] {$\displaystyle n$};
% Text Node
\draw (601,90) node   [align=left] {Time};
% Text Node
\draw (420,131.5) node   [align=left] {$\displaystyle 3$};
% Text Node
\draw (495,130.5) node   [align=left] {$\displaystyle .\ .\ .$};
% Text Node
\draw (182,54) node   [align=left] {$\displaystyle 1$};
% Text Node
\draw (301,54) node   [align=left] {$\displaystyle 1$};
% Text Node
\draw (421,54) node   [align=left] {$\displaystyle 1$};
% Text Node
\draw (571,54) node   [align=left] {$\displaystyle 1$};

\end{tikzpicture} 
```

10. (More details in the course "Life Contingencies I"). We need to define a random variable $T_x$ = the remaining future life time of a life aged $x$. 


```{tikz, tikz-sol2, fig.ext = 'png', cache=TRUE, echo = FALSE, fig.align="center"}

\tikzset{every picture/.style={line width=0.75pt}} %set default line width to 0.75pt        

\begin{tikzpicture}[x=0.75pt,y=0.75pt,yscale=-1,xscale=1]
%uncomment if require: \path (0,279); %set diagram left start at 0, and has height of 279

%Straight Lines [id:da8691686097400964] 
\draw    (140.6,111.2) -- (494.8,110.4) ;
\draw [shift={(496.8,110.4)}, rotate = 539.87] [color={rgb, 255:red, 0; green, 0; blue, 0 }  ][line width=0.75]    (10.93,-3.29) .. controls (6.95,-1.4) and (3.31,-0.3) .. (0,0) .. controls (3.31,0.3) and (6.95,1.4) .. (10.93,3.29)   ;
%Straight Lines [id:da9474951160801843] 
\draw    (181,106) -- (181,117) ;
%Straight Lines [id:da43730719784498717] 
\draw    (420,105) -- (420,116) ;
%Straight Lines [id:da5347119577328068] 
\draw    (421,69) -- (420.53,98) ;
\draw [shift={(420.5,100)}, rotate = 270.92] [color={rgb, 255:red, 0; green, 0; blue, 0 }  ][line width=0.75]    (10.93,-3.29) .. controls (6.95,-1.4) and (3.31,-0.3) .. (0,0) .. controls (3.31,0.3) and (6.95,1.4) .. (10.93,3.29)   ;

% Text Node
\draw (180,132.5) node   [align=left] {$\displaystyle x$};
% Text Node
\draw (420,131.5) node   [align=left] {$\displaystyle x\ +\ T_{x}$};
% Text Node
\draw (182,54) node   [align=left] {$ $};
% Text Node
\draw (421,54) node   [align=left] {$\displaystyle 1$};


\end{tikzpicture}
```


The quantity of interest is the present value of the death benefit assuming the interest rate of $i\%$ p.a. effective. It is also a random variable,
  $$PV = \frac{1}{(1+i)^{T_x}}.$$ It turns out that the premium rate of this whole life insurance is $E[PV]$, the expected value of the present value, $PV$. 


# Solutions to Tutorial 2

1. The solutions to each question are as follows:
    
    1. $(1.03)^3(1.04)^{2.5} (1.02)^{12} = 1.528611$
    2. $5000A(0.5,2.75) = 5000(1.03)(1.04)^{2.5} (1.02)^{9} = 6788.786068$
    3. We first find the rate $j\%$ per month effective that is equivalent to the rate of $4\%$ per half-year effective.
    $$j = (1.04)^{1/6} - 1 = 0.00656.$$
    The accumulated value is $100A(1+2/12, 3 + 7/12 ) = 100(1+j)^{10}(1.02)^{19} = 155.522118.$
    4. $25000V(0,1.5) = \frac{25000}{(1.03)^3(1.04)^{1.5}} = 21571.39968.$
    5. $8000V(0.25,2.75) = \frac{8000}{(1.03)^2(1.04)^{2.5}(1.02)^{9}} = 5720.455921.$
    6. $V(0.5,1.75) = \frac{1}{(1.03)(1.04)^{2}} = 0.897627.$

2.  The solutions to each question are as follows:
     
      1. With $i = 7.25\%$ per time period, $V(4) = 100 (1+i)^4 - 30(1+i)^3 - 30 (1+i)^2 + 100 (1+i) - 30 = 138.041762.$
    2. $V(8) = V(4)\cdot (1+i)^4 = 182.641597.$
    3. $PV(0) = V(4)\cdot (1+i)^{-4} = 104.332903.$


3.  The solutions to each question are as follows:
     
      1. With $ = 6\%$ per time period, $V(5) = 5000 (1+i)^5 - 2000(1+i)^{3.75} - 1000 (1+i)^{2.25} + 4000 (1+i)^{1.5} - 500(1+i) = 6897.948585.$
      2. $V(2) = V(5)(1+i)^{-3} = 5791.650645.$
      3. $PV(0) = V(5)(1+i)^{-5} = 5154.548456.$
      
4. The solutions to each question are as follows:
  
    1. $V(1/1/2019) = 100(1.04)(1.03)^{3.5}(1.015)^{15} - 30 (1.03)^{3.5}     (1.015)^{15}- 30 (1.03)^{1.5} (1.015)^{15} + 100 (1.015)^{12} - 30 = 152.955693.$
    2. $PV(0)= V(1/1/2015) = \frac{152.955693}{(1.04)(1.03)^{3.5}(1.015)^{15}} =106.074596.$
    3. $V(1/7/2017) = PV(0)(1.04)(1.03)^3 = 120.546998.$

# Solutions to Tutorial 3



1. Let $j$ be the effective rate per month equivalent to $i = 2$%. We have
  $$ j = (1.02)^{1/12}  - 1= 0.001652. $$
Hence, 

$$ PV(0) = 200 \ddot{a}^{j}_{120} + 300 \ddot{a}^{j}_{180} \left( \frac{1}{1.02} \right)^{10} = 60148.03. $$

2. The solutions to each question are as follows:

    1. The cashflows have been splitted into three periods: (a) from time point 0-5, (b) 5-10 and (c) time point 10 onward.
    $$PV(0) = 1000 ( a^{3\%}_{5} + 1.03^{-5} a^{4\%}_{5} +  1.03^{-5} 1.04^{-5} a^{5\%}_{5}) = 11489.49  $$

    2. We have
    $$PV(0) = 500 ( \ddot{a}^{3\%}_{5} + 1.03^{-5} \ddot{a}^{4\%}_{5} +  1.03^{-5} 1.04^{-5} \ddot{a}^{5\%}_{10}) = 7229.67  $$
    
    3. The accumuated value is
    $$100 (Is)^{3\%}_{5} (1.04)^5 (1.05)^{20} + \left[100 (Is)^{4\%}_{5} + 500 s^{4\%}_{5} \right] (1.05)^{20}  + \left[100 (Is)^{5\%}_{20} + 1000 s^{5\%}_{20} \right]= 78929.01  $$
    
    4. Let $i_1 = 3\%, i_2 = 4\%$ and $i_3 = 5\%$. The accumuated value is given by
    $$\begin{aligned} 
    V(18) &= \left[1000(1+i_1)^5 + 1000(1.02)(1+i_1)^4 + 1000(1.02)^2(1+i_1)^3 + \ldots + 1000(1.02)^4(1+i_1)\right](1.04)^5(1.05)^8   \\
    &+ \left[1000(1.02)^5(1+i_2)^5 + 1000(1.02)^6(1+i_2)^4 + 1000(1.02)^7(1+i_2)^3 + \ldots + 1000(1.02)^9(1+i_2)\right](1.05)^8   \\
    &+ \left[1000(1.02)^{10}(1+i_3)^8 + 1000(1.02)^{11}(1+i_3)^7 + 1000(1.02)^{12}(1+i_3)^6 + \ldots + 1000(1.02)^{17}(1+i_3)\right]  \\
    &= 1000(1.02)^5 \left[ \left(\frac{1+i_1}{1.02}\right)^5   + \left(\frac{1+i_1}{1.02}\right)^4 + \ldots + \left(\frac{1+i_1}{1.02}\right) \right](1.04)^5(1.05)^8 \\
    &+ 1000(1.02)^{10} \left[ \left(\frac{1+i_2}{1.02}\right)^5   + \left(\frac{1+i_2}{1.02}\right)^4 + \ldots + \left(\frac{1+i_2}{1.02}\right) \right](1.05)^8 \\
     &+ 1000(1.02)^{18} \left[ \left(\frac{1+i_3}{1.02}\right)^8   + \left(\frac{1+i_3}{1.02}\right)^7 + \ldots + \left(\frac{1+i_3}{1.02}\right) \right] 
    \end{aligned}$$
Let $1+j_1  = \frac{1+i_1}{1.02}$. Then, $j_1 = 0.009804$ and 
$$ \left[ \left(\frac{1+i_1}{1.02}\right)^5   + \left(\frac{1+i_1}{1.02}\right)^4 + \ldots + \left(\frac{1+i_1}{1.02}\right) \right] = \frac{(1+j_1)^5 - 1}{j_1/(1+j_1)} = 5.148995.$$
Let $1+j_2  = \frac{1+i_2}{1.02}$. Then, $j_2 = 0.019608$ and 
$$ \left[ \left(\frac{1+i_2}{1.02}\right)^5   + \left(\frac{1+i_2}{1.02}\right)^4 + \ldots + \left(\frac{1+i_2}{1.02}\right) \right] = 5.301921.$$
Let $1+j_3  = \frac{1+i_3}{1.02}$. Then, $j_3 = 0.029412$ and 
$$ \left[ \left(\frac{1+i_3}{1.02}\right)^8   + \left(\frac{1+i_3}{1.02}\right)^7 + \ldots + \left(\frac{1+i_3}{1.02}\right) \right]  = 9.134790.$$
Therefore, $V(18) = 32814.45$.

    5. The present value is 
    
$$\begin{aligned}
    PV(0) &= \left( \frac{200}{(1.03)^4} + \frac{200}{(1.03)^5}\right) + 200 a^{0.04}_5 (1.03)^{-5} + 200 a^{0.05}_{3} (1.03)^{-5} (1.04)^{-5} \\
    &= 350.2192 + 768.0362 + 386.1574 = 1504.413
\end{aligned}$$

3. The solutions to each question are as follows:

    1. $240000 (1.04)^5 = 291996.7$
    2. The interest amounts are $0.04\times 240000 = 9600.$
    3. By the Principle of Equivalence, we have
    $$ 240000 = X a^{0.04}_{5}. $$
    This gives X = 53910.51.
    4. Level installments are payable monthly, which follows
    $$ 240000 = Y a^{j}_{60}, $$
    where $j = (1.04)^{1/12} - 1$. This gives Y = 4412.23.
    
    
4. The person retires in 30 years, when his salary is expected to be 
$20000 \times (1.03)^{30} = 48545.25.$ 
The first payment will be half of this which is equal to 24272.62.
The present value at age 60 of his pension is
$$  24272.62 \times \ddot{a}^{0.029412}_{26} = 449717.9$$ (the precise value is 449719.051954).
Here we use $\frac{1.05}{1.02} = 1.029412$ and the annuity is paid from the 60th to the 85th birthday inclusive so there are 26 payments made in advance.
Therefore, the present value of this at age 30 is
$$ 449717.9 \times (1.05)^{-10} \times (1.04)^{-20} = 126002.9. $$
(the precise value is 126003.181173)
