

# Analysing data with pivot tables

Excel provides a powerful tool namely **pivot table** to summarise,
analyse, explore and present data.

-   Users can simply create useful summary of data and rearrange the
    information in any form with a few mouse clicks.

-   Pivot tables can create frequency distributions and
    cross-tabulations of several different data dimensions.

-   The users can also create **pivot charts** based on pivot tables,
    which provide meaningful, graphical data representation.

The following examples illustrate how to create pivot tables in Excel.
The dataset used in the examples contains data on sales from a
superstore The information on this data includes

-   Order and ship dates,

-   Ship modes,

-   Customer details,

-   Product details,

-   Sale and profit amounts.

The file can be downloaded from
https://community.tableau.com/docs/DOC-1236.

#### Example 1 {#example-1 .unnumbered}


Suppose that the manager is interested in profits, broken down by region
and sub-category. Instead of sorting the data and creating formulas to
answer the question, you can summarise the data by creating a pivot
table, which can be done in the following steps:

1.  Select any cell or table containing the data.

2.  From the **Insert** tab and click **PivotTable**.

3.  Specify the data and location for the pivot table in the
    **PivotTable dialog box**.

4.  A blank **PivotTable** and **PivotTable Fields List** will appear.

5.  Drag the field names (or column headers) at the top to one of the
    four boxes at the bottom of the **PivotTable Fields List**.

    For this example,

    -   **Drag the Profit field into the Values area**. At this point,
        the pivot table displays the total of all the values in the
        Profit column.

    -   **Drag the Sub-Category field into the Row Labels area**. The
        pivot table shows the total profit for each of the sub
        categories.

    -   **Drag the Region field into the Column Labels area**. The pivot
        table shows the total profit for each of the sub categories,
        cross-tabulated by region.

6.  The pivot table will calculate and summarise the selected fields.
    The result is shown in the Table [1](#Table1){reference-type="ref"
    reference="Table1"}.

```{=html}
<!-- -->
```
1.  The pivot table automatically updates the table with every change
    you make in the PivotTable Field List.

2.  You can sort data in a PivotTable. Just right-click any cell in the
    column to sort and choose Sort from the short-cut menu.

3.  You can apply number formatting, for example changing the Number
    Format to Currency.

4.  Pivot table data is usually summarised using a sum. You can also
    summarise your data using different summary techniques, such as Sum,
    Count, Average, etc.

::: {#Table1}
   Sum of Profit      Region                                    
  --------------- ---------- ----------- ---------- ----------- -------------
   Sub-Category      Central        East      South        West   Grand Total
    Accessories      7251.63    11195.86    7004.54     16484.6      41936.64
    Appliances      -2638.62     8391.41    4123.94     8261.27      18138.01
        Art          1195.16     1899.94    1058.59      2374.1       6527.79
      Binders       -1043.64    11267.93    3900.66     16096.8      30221.76
     Bookcases       -1997.9    -1167.63    1339.49    -1646.51      -3472.56
      Chairs         6592.72     9357.77    6612.09     4027.58      26590.17
      Copiers       15608.84    17022.84    3658.91    19327.24      55617.82
     Envelopes       1777.53     1812.41    1465.48     1908.76       6964.18
     Fasteners        236.62      263.99     173.72      275.19        949.52
    Furnishings     -3906.22     5881.41    3442.68     7641.27      13059.14
      Labels         1073.08     1129.28    1040.77     2303.12       5546.25
     Machines       -1486.07     6928.64   -1438.89     -618.93       3384.76
       Paper          6971.9     9015.37    5947.06    12119.24      34053.57
      Phones        12323.03    12314.69   10767.28     9110.74      44515.73
      Storage        1969.84     8389.37     2274.3     8645.32      21278.83
     Supplies        -661.89    -1155.14       1.88      626.05       -1189.1
      Tables        -3559.65   -11025.38   -4623.06     1482.61     -17725.48
    Grand Total     39706.36    91522.78   46749.43   108418.45     286397.02

  : Table 1: The pivot table from Example 1.
:::

## Filters

Filters can be used to display part of your data that you need. For
example, you can determine how various discount rates affect the
profits.

1.  Drag a field to the **Filters** section. In this example, we will
    use Discount field.

2.  The **filter** will appear above the pivot table. Then use a
    drop-down list to filter the displayed data by one or more items.

The pivot table filltered by discount field is shown in Table
[2](#Table2){reference-type="ref" reference="Table2"}.

::: {#Table2}
     Discount            0.5                                  
  --------------- ---------- ---------- ---------- ---------- -------------
   Sum of Profit      Region                                  
   Sub-Category      Central       East      South       West   Grand Total
     Bookcases                 -4255.81                            -4255.81
     Machines                             -7635.23                 -7635.23
      Tables        -4309.74                         -4305.64      -8615.39
    Grand Total     -4309.74   -4255.81   -7635.23   -4305.64     -20506.43

  : Table 2: The pivot table is filtered by discount.
:::

## Modifying the pivot table

You can add further summary information by using the **PivotTable Fields
List**. For example, you can add a second field (category) to the Row
Label area. Here you also need to change the order in which the fields
are listed, i.e. Category should be on the top level followed by
sub-category. Table [3](#Table3){reference-type="ref"
reference="Table3"} shows the pivot table when two fields are added in
row labels.

::: {#Table3}
       Sum of Profit                         Region                                    
  ----------------------- -------------- ---------- ----------- ---------- ----------- -------------
         Category         Sub-Category      Central        East      South        West   Grand Total
         Furniture        Bookcases         -1997.9    -1167.63    1339.49    -1646.51      -3472.56
                          Chairs            6592.72     9357.77    6612.09     4027.58      26590.17
                          Furnishings      -3906.22     5881.41    3442.68     7641.27      13059.14
                          Tables           -3559.65   -11025.38   -4623.06     1482.61     -17725.48
      Furniture Total                      -2871.05     3046.17    6771.21    11504.95      18451.27
      Office Supplies     Appliances       -2638.62     8391.41    4123.94     8261.27      18138.01
                          Art               1195.16     1899.94    1058.59      2374.1       6527.79
                          Binders          -1043.64    11267.93    3900.66     16096.8      30221.76
                          Envelopes         1777.53     1812.41    1465.48     1908.76       6964.18
                          Fasteners          236.62      263.99     173.72      275.19        949.52
                          Labels            1073.08     1129.28    1040.77     2303.12       5546.25
                          Paper              6971.9     9015.37    5947.06    12119.24      34053.57
                          Storage           1969.84     8389.37     2274.3     8645.32      21278.83
                          Supplies          -661.89    -1155.14       1.88      626.05       -1189.1
   Office Supplies Total                    8879.98    41014.58   19986.39    52609.85      122490.8
        Technology        Accessories       7251.63    11195.86    7004.54     16484.6      41936.64
                          Copiers          15608.84    17022.84    3658.91    19327.24      55617.82
                          Machines         -1486.07     6928.64   -1438.89     -618.93       3384.76
                          Phones           12323.03    12314.69   10767.28     9110.74      44515.73
     Technology Total                      33697.43    47462.04   19991.83    44303.65     145454.95
        Grand Total                        39706.36    91522.78   46749.43   108418.45     286397.02

  : Table 3: Two fields are used for row labels.
:::

#### Example 2 {#example-2 .unnumbered}


Create a pivot table to answer the following questions

1.  What are the total sales obtained from the top 5 customer who have
    spent the most, broken down by sub-category? How many orders did
    each customer have for each product?

2.  How does the sales in the Central region compared with the other
    regions combined?

3.  In which region does the superstore obtain the highest profit for
    each year?

4.  Create a frequency distribution of the profit, filtered by year.

## Working with Nonnumeric Data

Pivot tables can be used for nonnumeric data. In this case, a useful
pivot table can be created that counts the items rather than sums of
them.

The following Pivot table cross-tabulates the segment for each
combination of segment and region. Here, we specify each of the Pivot
table fields as follows:

-   The Segment field is used for the Columns.

-   The Region field is used for the Rows.

-   The Segment field is also used for the Values and is summarised by
    Count.

-   A second instance of the Segment field is added to the Values
    section. To display percentages, in Field Setting, choose Show
    Values As Percent of Column Total.

width=1

                Segment                                                                                                                                                                   
  ------------- ------------------ -------------------------------- ------------------ -------------------------------- ------------------ -------------------------------- ------------- ------------------
                Consumer                                            Corporate                                           Home Office                                         Total Count   Total Percentage
                Count of Segment   Count of Segment by Percentage   Count of Segment   Count of Segment by Percentage   Count of Segment   Count of Segment by Percentage                 
  Central       1212               23.35%                           673                22.28%                           438                24.57%                           2323          23.24%
  East          1469               28.30%                           877                29.04%                           502                28.15%                           2848          28.50%
  South         838                16.14%                           510                16.89%                           272                15.26%                           1620          16.21%
  West          1672               32.21%                           960                31.79%                           571                32.02%                           3203          32.05%
  Grand Total   5191               100.00%                          3020               100.00%                          1783               100.00%                          9994          100.00%

  : Table 4: The Pivot Table for Nonnumeric Data
