% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{lmodern}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  pdftitle={SCMA329 Practical Mathematical Financial Modeling},
  pdfauthor={Pairote Satiracoo},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage[margin=1in]{geometry}
\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{5}
\usepackage{booktabs}
\usepackage{amsthm}
\usepackage{LectureNoteMacro}
\usepackage{bbm}
\usepackage{mathtools}
\usepackage{tikz}
\makeatletter
\def\thm@space@setup{%
  \thm@preskip=8pt plus 2pt minus 4pt
  \thm@postskip=\thm@preskip
}
\makeatother
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\usepackage[]{natbib}
\bibliographystyle{plainnat}

\title{SCMA329 Practical Mathematical Financial Modeling}
\author{Pairote Satiracoo}
\date{2021-11-13}

\usepackage{amsthm}
\newtheorem{theorem}{Theorem}[section]
\newtheorem{lemma}{Lemma}[section]
\newtheorem{corollary}{Corollary}[section]
\newtheorem{proposition}{Proposition}[section]
\newtheorem{conjecture}{Conjecture}[section]
\theoremstyle{definition}
\newtheorem{definition}{Definition}[section]
\theoremstyle{definition}
\newtheorem{example}{Example}[section]
\theoremstyle{definition}
\newtheorem{exercise}{Exercise}[section]
\theoremstyle{definition}
\newtheorem{hypothesis}{Hypothesis}[section]
\theoremstyle{remark}
\newtheorem*{remark}{Remark}
\newtheorem*{solution}{Solution}
\begin{document}
\maketitle

{
\setcounter{tocdepth}{2}
\tableofcontents
}
\hypertarget{dates-and-date-functions}{%
\section{Dates and date functions}\label{dates-and-date-functions}}

Dates and date functions will be discussed in this section. Depending on
the system setting, the dates used in this section corresponds to the
U.S. setting, i.e.~month/day/year. Thus, 7/1/2017 corresponds to 1 July
2017.

The following date formats are recognized by Excel:

\begin{itemize}
\item
  7/1/2017, 7/1/17
\item
  7-1-2017, 7-1-17,
\item
  7-1/2017, 7-1/17,
\item
  July 1, 2017
\item
  1-Jul-2017
\end{itemize}

if the date input is without the year, then it is the date on the
current year, i.e.~7-1, 7/1, July 1, Jul 1, corresponds to 1 July 2018.

\hypertarget{inconsistent-date-entries}{%
\subsection{Inconsistent date entries}\label{inconsistent-date-entries}}

\begin{example}
\protect\hypertarget{exm:unlabeled-div-1}{}\label{exm:unlabeled-div-1}

\emph{What will be the output when we enter dates by using the
following two digits for the years:}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  \emph{7/1/01}
\item
  \emph{7/1/60}
\end{enumerate}

\end{example}

Excel interprets two digit years between 00 and 29 as 21st century
dates, and two digit years between 30 and 99 as 20th century dates.

\hypertarget{date-serial-number}{%
\subsection{Date serial number}\label{date-serial-number}}

Excel stores dates as sequential serial numbers so that they can be used
in calculations. For example,

\begin{itemize}
\item
  1 January 1900 is serial number 1,
\item
  1 January 2018 is serial number 43101 because it is 43101 days after
  1 January 1900.
\end{itemize}

\hypertarget{date-functions}{%
\subsection{Date functions}\label{date-functions}}

The list of date functions can be seen by choosing

\textbf{Formulas \(\rightarrow\) Function Library \(\rightarrow\) Function Library \(\rightarrow\) Date \& Time}.

\begin{longtable}[]{@{}ll@{}}
\toprule
\textbf{Function} & \textbf{Description} \\
\midrule
\endhead
DATE & Returns the serial number of a particular date \\
DATEVALUE & Converts a date in the form of text to a serial number \\
DAY & Converts a serial number to a day of the month \\
DAYS & Returns the number of days between two dates \\
WEEKDAY & Converts a serial number to a day of the week \\
NETWORKDAYS & Returns the difference between two dates, excluding weekend days (Saturdays and Sundays) \\
WORKDAY & Returns a number that represents a date that is the indicated number of working days before or after a date (the starting date) \\
EDATE & Returns the serial number that represents the date that is the indicated number of months before or after a specified date \\
EOMONTH & Returns the serial number for the last day of the month that is the indicated number of months before or after a specified date \\
YEARFRAC & Returns a decimal value that represents fractional years between two dates \\
\bottomrule
\end{longtable}

For a complete list, see the date and time functions available online.
More detailed examples are also given in the Excel lab.

\hypertarget{working-with-texts}{%
\section{Working with Texts}\label{working-with-texts}}

In this section, we will see how Excel handles text strings, and how we
use text functions to modify and manipulate text strings. First, we give
a note regarding texts in Excel.

\begin{itemize}
\item
  A single cell can hold up to 32,000 characters. In case you need to
  display a lot of text in a worksheet, then use a text box (Choose
  Insert \(\Rightarrow\) Text \(\Rightarrow\) Text Box). It will be easier
  to edit texts in the text box than in cells.
\item
  Sometimes, when you download numerical data from the internet or
  database, the imported values are treated as text, i.e.~when you do
  a calculation with such data, you will get a \#VALUE error. When a
  number is not treated as a number, there will be an error indicator.
  By clinking to expand a list of options, you can then convert it to
  the number.
\item
  Another issue that you may encounter is about currency that uses
  different characters to separate thousands or decimals.
  \url{https://en.wikipedia.org/wiki/Decimal_separator}
\end{itemize}

\hypertarget{text-functions}{%
\subsection{Text functions}\label{text-functions}}

The following Excel functions can be used to modify text strings in the
format you need. Alternatively, one may extract data by using the
Convert Text To Columns Wizard (choose Data \(\Rightarrow\) Text To
Columns).

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  RIGHT(text,{[}n{]}) returns the last \(n\) characters in a text string.
\item
  LEFT(text, {[}n{]}) returns the first \(n\) characters in a text string.
\item
  MID(text, start\_num, num\_chars) returns num\_char characters from a
  text string, starting at start\_num.
\item
  TRIM(text) removes all spaces from text except for single spaces
  between words. Use TRIM when text strings have irregular spacing.
\item
  LEN(text) returns the number of characters in a text string.
\item
  FIND(find\_text, within\_text, {[}start\_num{]}) return the location at
  or after character start\_num of the first character of find\_text in
  within\_text.
\item
  SEARCH(find\_text, within\_text, {[}start\_num{]}) has the same syntax as
  FIND, but it is not case sensitive.
\item
  SUBSTITUTE(text, old\_text, new\_text, {[}instance\_num{]}) is used to
  replace new\_text for old\_text in a text string. Here Instance\_num is
  optional. It specifies which occurrence of old\_text you want to
  replace with new\_text. If you specify instance\_num, only that
  instance of old\_text is replaced. Otherwise, every occurrence of
  old\_text in text is changed to new\_text.
\end{enumerate}

\hypertarget{character-codes}{%
\subsection{Character codes}\label{character-codes}}

Excel uses the standard ASCII character set. Therefore, each character
has its own code. For example, to get the code number of ``A'', simply
type

=CODE(``A''), which returns the code number 65.

The CHAR function reverses the role of CODE function, i.e.

=CHAR(65), which returns the letter A. The input for the CHAR function
should be a value between 1 and 255.

For the complete list of ASCII codes, please visit
\url{https://theasciicode.com.ar}

\begin{example}
\protect\hypertarget{exm:unlabeled-div-2}{}\label{exm:unlabeled-div-2}

\emph{Create an Excel file to list all the first 255 ASCII
codes. It is a good idea to compare the outputs with those from the
website above.}

\end{example}

\hypertarget{determining-whether-two-string-are-identical}{%
\subsection{Determining whether two string are identical}\label{determining-whether-two-string-are-identical}}

In order to determine whether strings in cell A1 and A2 have the same
contents, we use = A1 = A2, which returns either TRUE or FALSE. Note
that the comparison is not case-sensitive.

Alternative, the function that provides an exact, case-sensitive
comparison is EXACT function.

\hypertarget{joining-two-or-more-cells}{%
\subsection{Joining two or more cells}\label{joining-two-or-more-cells}}

To join two or more cells, Excel uses an ampersand \&. For example if the
string ``the effective interest rate per annum'' is in A1 and the value of
5\% (formatted value) is in B1. Then use the formula

= A1 \& '' is '' \& B1, which returns the effective interest rate per annum
is 0.05.

A better solution is to use the TEXT function to format the value as
text as follows.

= A1 \& '' is '' \& TEXT(B1,'' 0.00\%``) , which returns the effective interest
rate per annum is 0.05.

Use \textbf{Home Format Format cells} to obtain the list of various text
formats.

For example, if A1 contains the principle of \$10,000, then

= ``The principle is'' \& TEXT(A1, '' \$\#,\#\#0''), which returns The
principle is \$10,000.

The following table gives examples that are format with TEXT function.

\begin{verbatim}
=TEXT(1234.567,"$#,##0.00")     
Currency with a thousands separator and 2 decimals, like $1,234.57. Note that Excel rounds the value to 2 decimal places.

=TEXT(TODAY(),"MM/DD/YY")
Today's date in MM/DD/YY format, like 03/14/12

=TEXT(TODAY(),"DDDD")
Today's day of the week, like Monday

=TEXT(NOW(),"H:MM AM/PM")
Current time, like 1:29 PM

=TEXT(0.285,"0.0%")
Percentage, like 28.5%

=TEXT(4.34 ,"# ?/?")
Fraction, like 4 1/3

=TRIM(TEXT(0.34,"# ?/?"))
Fraction, like 1/3. Note this uses the TRIM function to remove the leading space with a decimal value.

=TEXT(12200000,"0.00E+00")
Scientific notation, like 1.22E+07

=TEXT(1234567898,"[<=9999999]###-####;(###) ###-####")
Special (Phone number), like (123) 456-7898

=TEXT(1234,"0000000")
Add leading zeros (0), like 0001234
\end{verbatim}

The TEXT function will convert numbers to text. It is best practice to
keep your original values in one cell, and formatted number in another
cell. When you do calculation, you should refer to the cells containing
original values.

\hypertarget{interest-rate-present-values-and-cashflows}{%
\section{Interest Rate, Present Values and Cashflows}\label{interest-rate-present-values-and-cashflows}}

\hypertarget{working-with-a-single-cashflow-in-excel}{%
\subsection{Working with a single cashflow in Excel}\label{working-with-a-single-cashflow-in-excel}}

\hypertarget{how-to-calculate-the-future-value-of-a-single-cashflow}{%
\subsubsection{How to calculate the future value of a single cashflow}\label{how-to-calculate-the-future-value-of-a-single-cashflow}}

Suppose an amount \(C\) is deposited in an account that pays a fixed
interest at the rate of \(i\)\% per time units. Then after \(t\) time units,
the deposit will have accumulated to \[C (1+i)^t.\]

In Excel, the function FV calculates the future value of a single
investment (and also periodic constant payments) and a constant interest
rate.

The syntax of the function is:

\[\text{FV(rate, nper, pmt, [pv], [type])},\]

where

\begin{itemize}
\item
  rate is the interest rate per period
\item
  nper is the number of periods over which the investment is made.
\item
  pmt (used for an annuity type) is the payment made each period and
  cannot change over the life of the annuity.
\item
  pv (optional) is an additional cash flow now (time 0)
\item
  fv is an additional cash flow nper periods from now.
\item
  type (optional) is an optional argument that defines whether the
  payment is made at the start or the end of the period:

  0 - the payment is made at the end of the period;

  1 - the payment is made at the start of the period.

  If the {[}type{]} argument is omitted, it takes on the default value
  of 0.
\end{itemize}

The following timeline illustrates the cashflows used for the FV
function (assuming that the payments (pmt) are made in arrears).

\begin{figure}

{\centering \includegraphics{SCMA329ExcelBookdownproj_files/figure-latex/tikz-ex-1} 

}

\caption{Timeline of cashflows for FV function}\label{fig:tikz-ex}
\end{figure}

\textbf{Note} For a single cash flow, we set pmt argument to be 0, as there are no
ongoing payments after the initial investment.

\begin{example}
\protect\hypertarget{exm:unlabeled-div-3}{}\label{exm:unlabeled-div-3}

\emph{You plan to invest today with an interest rate of 3\% per
year effective. How much money will you accumulate at the end of 2
years?}

\end{example}

\textbf{Solution:} The accumulation of today in 2 years can be calculated by Excel as
\[\text{FV}(3\%, 2, 0, -100).\]

\hypertarget{how-to-calculate-the-present-value-of-a-single-cashflow}{%
\subsubsection{How to calculate the present value of a single cashflow}\label{how-to-calculate-the-present-value-of-a-single-cashflow}}

Similarly, the present value of a future cashflow \(C\) required at time
\(t\) time units at a fixed interest of \(i\)\% per time units can be
calculated as \[\frac{C}{(1+i)^t}.\] In Excel, the function PV
calculates the present value of a single investment (and also periodic
constant payments) and a constant interest rate. The syntax of the
function is:

\[\text{PV(rate, nper, pmt, [fv], [type])}\] where fv is an additional
cash flow nper periods from now.

\begin{example}
\protect\hypertarget{exm:unlabeled-div-4}{}\label{exm:unlabeled-div-4}

\emph{How much should you deposit into the account with an
interest of 8\% so that 10 years from now its value would be ?}

\end{example}

\textbf{Solution:}
The present value of today in 10 years can be calculated by Excel as
\[\text{PV}(8\%, 10, 0, -1000).\]

\hypertarget{present-values-of-a-series-of-cashflows}{%
\subsection{Present values of a series of cashflows}\label{present-values-of-a-series-of-cashflows}}

Consider a series of cashflows defined by

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  the times of payments (cashflows), denoted by \(t_1, t_2, \ldots,\)
  and
\item
  the amount of payments, denoted by \(C_{r}\) (in short for \(C_{t_r}\)),
  which will be paid at time \(t_r\), for \(r = 1,2, \ldots\). The amounts
  can be positive or negative
\end{enumerate}

The present value at any time \(t\) of this series of cashflow is
\[PV(t) = \sum_{r=1}^\infty C_r (1 + i)^{t - t_r} = \sum_{r=1}^\infty C_r v^{t _r - t}\]
where \(i\) is the effective rate of interest and \(v = 1/(1+i)\).

\begin{figure}

{\centering \includegraphics{SCMA329ExcelBookdownproj_files/figure-latex/tikz-ex2-1} 

}

\caption{Timeline of a series of cashflows}\label{fig:tikz-ex2}
\end{figure}

\textbf{Notes}
1. At a fixed effective rate of interest, the original series of
cashflows is equivalent to a single payment of amount \(PV(t)\) at
time \(t\).

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{1}
\tightlist
\item
  If two different series of cashflows have the same \(PV\) at one time
  at a given effective rate of interest, then they have the same \(PV\)
  at any time at that effective rate of interest.
\end{enumerate}

\hypertarget{level-annuities-certain}{%
\subsubsection{Level Annuities certain}\label{level-annuities-certain}}

An \emph{annuity} is a regular series of payments (cashflows). When the
payments are certain which are payable for a definite period of time, we
call it an \emph{annuity certain}.

\begin{itemize}
\item
  If the payments are made at the end of each time period, they are
  paid \emph{in arrear}.
\item
  Otherwise, payments are made at the beginning of each time period,
  they are pain \emph{in advance}.
\item
  An annuity paid in advance is also known as an \emph{annuity due}
\item
  If each payment is for the same amount, this is a \emph{level} annuity.
\end{itemize}

\begin{example}
\protect\hypertarget{exm:unlabeled-div-5}{}\label{exm:unlabeled-div-5}

\emph{Let \(i\) be the constant effective rate of interest per
time unit. In Excel, one can calculate the accumulated value of a level
annuity certain having cashflow of pmt unit at the end of each of the
next \(n\) time units by \[\text{FV}(i\%, n, pmt, 0).\] The cashflows of
this annuity is shown in the timeline below.}

\begin{figure}

{\centering \includegraphics{SCMA329ExcelBookdownproj_files/figure-latex/tikz-ex3-1} 

}

\caption{Level Annuity Certain}\label{fig:tikz-ex3}
\end{figure}

\textbf{Note}
\emph{The last argument of the above syntax, {[}pv{]} (optional) which is an
additional cash flow now (at time 0), has been set to 0.}

\end{example}

\begin{example}
\protect\hypertarget{exm:unlabeled-div-6}{}\label{exm:unlabeled-div-6}

\emph{Let \(i\) be the constant effective rate of interest per
time unit. In Excel, one can calculate the present value at time 0 of a
level annuity certain having cashflow of pmt unit at the end of each of
the next \(n\) time units by \[\text{PV}(i\%, n, pmt, 0).\]}

\end{example}

The timeline of these cashflows is shown in the figure below:

\begin{figure}

{\centering \includegraphics{SCMA329ExcelBookdownproj_files/figure-latex/tikz-ex4-1} 

}

\caption{Level Annuity Certain}\label{fig:tikz-ex4}
\end{figure}

\textbf{Note}
The last argument of the above syntax, {[}fv{]} (optional) which is an
additional cash flow at time \(n\), has been set to 0.

\begin{example}
\protect\hypertarget{exm:unlabeled-div-7}{}\label{exm:unlabeled-div-7}

\emph{Given the effective rate of interest of \(8\%\) p.a., use
Excel to calculate}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  \emph{the accumulation at 12 years of payable yearly in arrear for the
  next 12 years.}
\item
  \emph{the present value now of ,000 payable yearly in arrear for the next
  6 years.}
\item
  \emph{the present value now of ,000 payable half-yearly in arrear for the
  next 12.5 years.}
\end{enumerate}

\end{example}

\begin{example}
\protect\hypertarget{exm:unlabeled-div-8}{}\label{exm:unlabeled-div-8}

\emph{Let \(i = 4\%\) effective per time unit. Cashflows are
given as follows:}

\begin{itemize}
\item
  \emph{\(C_1 = 200\) at time \(t_1 = 1\).}
\item
  \emph{\(C_2 = 300\) at time \(t_2 = 3\).}
\item
  \emph{\(C_3 = -100\) at time \(t_3 = 5\).}
\item
  \emph{\(C_4 = -50\) at time \(t_4 = 6\).}
\end{itemize}

\emph{Develop the model using Excel to calculate}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  \emph{the accumulation at time \(t = 7\).}
\item
  \emph{the present value at time \(t = 0\).}
\item
  \emph{the present value at time \(t = 4\).}
\end{enumerate}

\end{example}

\hypertarget{lookup-formulas-and-data-tables}{%
\section{Lookup Formulas and Data Tables}\label{lookup-formulas-and-data-tables}}

\hypertarget{lookup-function}{%
\subsection{Lookup function}\label{lookup-function}}

Lookup function can be used to return (or retrieve) a value from a table
or a range of data. For example, use lookup function to find some
information such as date of birth, address etc. from a customer
database. Two useful lookup functions are \texttt{VLOOKUP} and \texttt{HLOOKUP}.

\begin{itemize}
\item
  The \texttt{VLOOKUP} function searches a value in the first column and
  returns a value in the same row from a column you specify in the
  table or array.
\item
  The \texttt{HLOOKUP} function searches a value in the top row and returns a
  value in the same column from a row you specify in the table or
  array.
\end{itemize}

The syntaxes for the \texttt{LOOKUP} functions are

\texttt{=VLOOKUP(lookup\ value,\ range\ containing\ the\ lookup\ value,\ the\ column\ number\ in\ the\ range\ containing\ the\ return\ value,\ {[}range\_lookup{]})}.

\texttt{=VLOOKUP(lookup\_value,\ table\_array,\ col\_index\_num,\ {[}range\_lookup{]})}.

\texttt{=HLOOKUP(lookup\_value,\ table\_array,\ row\_index\_num,\ {[}range\_lookup{]})}.

The \texttt{{[}range\_lookup{]}} is an optional which can be specified as \texttt{TRUE} for
approximate match or \texttt{FALSE} for an exact match.

\textbf{Notes}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  The EXCEL \texttt{LOOKUP} functions treat empty cells in the result range as
  \textbf{zeros}.
\item
  If the range\_lookup is \texttt{FALSE} and an exact match is not found, the
  function returns \#N/A.
\item
  If the range\_lookup is \texttt{TRUE} or omitted, the first column of the
  \texttt{VLOOKUP} table must be in ascending order. If lookup\_value is smaller
  than the the smallest value in the first column of the table\_array,
  then the function returns \#N/A.
\item
  Use \texttt{IFERROR} function to avoid the return \#N/A. Use the following
  syntax

  \texttt{=IFERROR(value,\ value\_if\_error)}

  (for example, \texttt{=IFERROR(VLOOKUP(...),"Value\ is\ not\ availble"} )
\item
  The wildcard character * and ? can be used when the range\_lookup
  argument is text.
\item
  The wildcard character ? refers to any single character, for example
  "analy?e" finds "analyse" and "analyze".
\item
  The wildcard character * refers to any number of characters, for
  example "bio*" finds "biology" and "biotechnology".
\end{enumerate}

\begin{example}
\protect\hypertarget{exm:unlabeled-div-9}{}\label{exm:unlabeled-div-9}

Import SET Index historical daily data starting from 1 January 2020 up
to now from
\url{https://www.investing.com/indices/thailand-set-historical-data}. Use
\texttt{LOOKUP} function to create the table showing

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  the closing price on the first working day of each month (not
  including holidays).
\item
  the closing price on the last working day of each month (not
  including holidays).
\end{enumerate}

Hint: use

\texttt{=WORKDAY(DATE(YEAR(A1),MONTH(A1),1)-1,1)} to return the first working day
of a month and

\texttt{=WORKDAY(DATE(YEAR(A1),MONTH(A1)+1,1),-1)} to return the last working day
of a month.

\end{example}

\begin{example}
\protect\hypertarget{exm:unlabeled-div-10}{}\label{exm:unlabeled-div-10}

Use the SET Index historical data above. On your selected cells, find
the lowest and highest closing prices and the dates when those occurred
(sorting data is not allowed).

\end{example}

\hypertarget{match-and-index-functions}{%
\subsection{MATCH and INDEX functions}\label{match-and-index-functions}}

The \texttt{MATCH} and \texttt{INDEX} functions are often used together to perform
lookups.

The \texttt{MATCH} function returns the relative position of a specified item in
a range of cells. For example, if the range A1:A3 contains the values 2,
4 and 6, then the formula

\texttt{=MATCH(4,A1:A3,0)} returns the number 2, i.e.~the second item in the
range.

The syntax for MATCH is

\texttt{=MATCH(lookup\_value,\ lookup\_array,\ {[}match\_type{]})}

The optional argument is match\_type consisting of 3 values, \(-1\), 0 and
1, that specify how the match is determined.

\begin{itemize}
\item
  If match\_type = 1 or omitted, then \texttt{MATCH} finds the largest value
  less than or equal to lookup\_value where lookup\_array must be in
  \textbf{ascending order}.
\item
  If match\_type = 0, then \texttt{MATCH} finds the \textbf{first value exactly equal
  to} lookup\_value.
\item
  If match\_type = \(-1\), then MATCH finds the smallest value greater
  than or equal to lookup\_value where lookup\_array must be in
  \textbf{descending order}.
\end{itemize}

The \texttt{INDEX} function returns a value from within a table or range. The
syntax for INDEX is

\texttt{=INDEX(array,\ row\_num,\ {[}column\_num{]})}

If array contains only one row or column, the corresponding row\_num or
column\_num argument is optional.

\hypertarget{data-tables}{%
\subsection{Data tables}\label{data-tables}}

Data tables allows you to create a table of values from

\begin{itemize}
\item
  a formula as one or two variables from the formula are varied, and
\item
  more formulas for various values of a single input cell.
\end{itemize}

As a result, you can examine a range of possible values when one or two
variables are systematically changed. For example, a data table can be
used to display the amount your investment will grow to for various
numbers of compounding.

\begin{example}
\protect\hypertarget{exm:unlabeled-div-11}{}\label{exm:unlabeled-div-11}

An amount of \(P\) is invested for \(n\) years at a nominal interest rate of
i\%. Create a worksheet to calculate the effective annual interest rate
you will earn and the accumulation at time \(n\) years for various numbers
of compounding periods per year including

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  annual compounding
\item
  semi-annual compounding
\item
  quarterly compounding
\item
  monthly compounding
\item
  bi-weekly compounding
\item
  weekly compounding
\item
  daily compounding
\end{enumerate}

\end{example}

\hypertarget{model-formulation}{%
\subsubsection*{Model formulation}\label{model-formulation}}
\addcontentsline{toc}{subsubsection}{Model formulation}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  \textbf{Set up input variables:} Referring to the corresponding excel
  file, create the labels for the input variables and enter the values
  in cells B4:B7.
\item
  \textbf{Calculate the output values:} The effective annual interest rate
  \(i\%\) which is equivalent to the given nominal rate \(i^{(p)}\)
  convertible \(p\) times a year can be calculated by
  \[i = \left(1 + \frac{i^{(p)}}{p} \right)^p - 1.\] Hence, the value
  of the investment at time \(n\) years is \[FV = P (1 + i)^n.\] The
  output values are calculated and placed in cells B10 and B11,
  respectively.
\item
  \textbf{Set up data table (a one-input data table) :}

  \begin{enumerate}
  \def\labelenumii{\arabic{enumii}.}
  \item
    Create the labels and values for different compounding
    frequencies.
  \item
    In cells C16 and D16, create the references to cells B10 and
    B11, which are the effective annual interest rate and future
    value of investment, respectively.

    The positions of the cells C16 and D16, the formulas used to
    calculate the required values, are \textbf{one row above and to the
    right} of the column of values. The data table is
    column-oriented because the variable values are in a column,
    B17:B23 in this example.
  \item
    Select the range of cells that contains the formulas and values
    that you want to substitute, i.e.~the range B16:D23.
  \item
    Choose Data
    What-If Analysis Data table. Then type the cell reference for
    the input cell, cell B5 in this case, in the \textbf{Column input
    cell} because the data table is column-oriented. Click OK and
    Excel will complete the data table.
  \end{enumerate}
\end{enumerate}

\textbf{Notes}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  A new formula can be added to the existing one-variable data table
  by typing the new formula in a blank cell to the right of the
  existing formula(s) in the top row of the data table. Then repeat
  Step 3.4 as given above.
\item
  The contents of the data table are generated with a multicell array
  formula (details will be discussed in a subsequent section):

  \texttt{\{=TABLE(,B5)\}}.
\end{enumerate}

\begin{example}
\protect\hypertarget{exm:unlabeled-div-12}{}\label{exm:unlabeled-div-12}

Suppose you borrow \(L\) from a bank to be repaid by the end of \(n\) years
at an interest rate of \(i\%\) per annum effective. If you agree to repay
the loan and the interest in level instalments throughout term of loan.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  Create a model to calculate the amount of annual instalments \(X\) for
  various values of number of instalments \(n\) and interest rate of
  \(i\%\) per annum effective.
\item
  Set up a two-input data table to show annual instalments \(X\) for
  different values of \(n\) and \(i\).
\item
  Comment on the results obtained.
\end{enumerate}

\end{example}

\hypertarget{analysing-data-using-goal-seeking-and-solver}{%
\section{Analysing data using Goal Seeking and Solver}\label{analysing-data-using-goal-seeking-and-solver}}

\hypertarget{analysing-data-using-goal-seeking}{%
\subsection{Analysing data using Goal Seeking}\label{analysing-data-using-goal-seeking}}

Goal Seek feature allows a user to find the value that is an input for a
formula (a single input cell) to produce a required result. For example,
given a series of cashflows \(C_1, C_2, \ldots C_n\) (positive and
negative) payable at times \(t_1, t_2, \ldots, t_n\), you can set up your
worksheet to calculate the present value at time 0 defined by
\[PV_i(0) = \sum_{i=1}^n C_i \left( \frac{1}{1+i} \right)^{t_i}.\] The
solution \(i\) of the equation \[PV_i(0) = 0,\] which is the yield of the
cashflows, can be directly obtained by using Goal Seek. Here the yield
\(i\) is the value for a worksheet input that makes the value of the
formula \(PV_i(0)\) (or the present value function expressed in terms of
\(i\)) match the goal, which is zero in this case.

\textbf{Note} Goal Seek works only with one variable input value. You can use the
Solver add-in when more than one input value is needed; for example,
both the loan amount and the monthly payment amount for a loan.

We first illustrate how to use Goal Seek to find the interest rate from
a loan in the following example.

\begin{example}
\protect\hypertarget{exm:exampleGoalSeek}{}\label{exm:exampleGoalSeek}

\emph{Suppose that you borrow 5,000 for a term of 3 years. The
loan is to be repaid by 3 level annual repayments of 2,010.57 at the end
of each year. Calculate the interest rate for this loan.}

\end{example}

\hypertarget{model-formulation-for-example-examplegoalseek}{%
\paragraph*{\texorpdfstring{Model formulation for Example \protect\hyperlink{exampleGoalSeek}{5.1}}{Model formulation for Example 5.1}}\label{model-formulation-for-example-examplegoalseek}}
\addcontentsline{toc}{paragraph}{Model formulation for Example \protect\hyperlink{exampleGoalSeek}{5.1}}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  \textbf{Set up input variables} Create the labels for the input variables
  in cells A4:A6 for loan amount, term of the loan, and payment,
  respectively. Then enter the values 5,000, 3 and 2,010.57 in cells
  B4-B6, respectively. Create the label for the output variable (i.e.
  the interest rate \(i\)). You may enter the guessing value for the
  interest rate, say for e.g.~\(i = 1\%\) in the corresponding cell
  (i.e.~the cell B9)
\item
  \textbf{Construct year-by-year cashflows} Use the guessing value of \(i\)
  to construct year-by-year cashflow to calculate the present value of
  the cashflows (in cell E12 in our example)
\item
  \textbf{Use Goal Seek to calculate the interest rate}. Choose

  \textbf{Data \(\rightarrow\) Data Tools \(\rightarrow\) What-If Analysis \(\rightarrow\) Goal Seek}

  \begin{enumerate}
  \def\labelenumii{\arabic{enumii}.}
  \item
    Then in the \textbf{Set cell} box, enter the reference for the cell
    that contains the formula (or the goal we want to match), i.e.
    cell E12.
  \item
    In the \textbf{To value} box, enter the result of the the formula,
    i.e.~the value of the present value of the cashflows which is 0.
  \item
    In the \textbf{By changing cell} box, enter the reference for the
    cell that you want to adjust, i.e.~cell B9.
  \end{enumerate}
\item
  \textbf{Goal Seek status box} then displays the target value and the
  value that excel calculated.
\end{enumerate}

\textbf{Note}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  In case that Goal Seek cannot find a solution but there is a
  solution to the problem.

  \begin{enumerate}
  \def\labelenumii{\arabic{enumii}.}
  \item
    You should change the value used in the by changing cell box to
    a value that should be close to the solution.
  \item
    Increase the Maximum Iterations setting which allows Excel to
    try more possible solutions. To set the Maximum Iterations, go
    to

    \textbf{File \(\rightarrow\) Excel \(\rightarrow\) Options\(\rightarrow\) Formula tab}
  \end{enumerate}
\item
  In order to increase the accuracy of the (approximated) solution,
  set the option value for Maximum Change (located in \textbf{Excel Options
  Formula tab}) to a small value. The defaul value is 0.001 which
  gives only 3 decimals accuracy.
\end{enumerate}

\begin{example}
\protect\hypertarget{exm:exampleYield}{}\label{exm:exampleYield}

\emph{Consider a transaction from an investment that offers}

\begin{itemize}
\item
  \emph{to pay an investor of amounts \(B_1, B_2, \ldots, B_n\) at time
  \(t_1, t_2, \ldots ,t_n\)}
\item
  \emph{in return for outlays (amounts to be paid by the investor) of
  amounts \(A_1, A_2, \ldots, A_n\) at these times, respectively.}
\end{itemize}

\emph{Only one of \(A_i\) and \(B_i\) will be non-zero in general. Make all the
important variables of the problem input variables. Build the model to
calculate the yield of the investment for the two examples in the
lecture note.}

\end{example}

\hypertarget{analysing-data-using-solver}{%
\subsection{Analysing data using Solver}\label{analysing-data-using-solver}}

Goal Seek has a limitation that can solve for only one adjustable cell.
Solver extends this Goal Seek function and can do the following:

\begin{itemize}
\item
  work with multiple adjustable cells.
\item
  specify constrains for the values of adjustable cells.
\item
  find an optimum value for a formula.
\item
  generate multiple solutions to a problem.
\end{itemize}

\hypertarget{a-simple-solver-example}{%
\subsection{A simple Solver example}\label{a-simple-solver-example}}

We will describe how to use Solver to solve same the problem as Goal
Seek.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  \textbf{Set up input variables} This is similar to Goal Seek section.
\item
  \textbf{Set up a formula for the output variable} This is similar to Goal
  Seek section.
\item
  \textbf{Use Goal Seek to calculate the interest rate}. Choose

  \textbf{Data \(\rightarrow\) Analysis \(\rightarrow\) Solver}

  \begin{enumerate}
  \def\labelenumii{\arabic{enumii}.}
  \item
    Then in the \textbf{Set Objective} box, enter the reference for the
    cell that contains the formula, i.e.~cell B6.
  \item
    In the \textbf{To} box, choose \textbf{Value of} box and then enter the
    result of the the formula.
  \item
    In the \textbf{By Changing Variable cells} box, enter the reference
    for the cell that you want to adjust, i.e.~cell B5.
  \end{enumerate}
\end{enumerate}

\hypertarget{analysing-data-with-pivot-tables}{%
\section{Analysing data with pivot tables}\label{analysing-data-with-pivot-tables}}

Excel provides a powerful tool namely \textbf{pivot table} to summarise,
analyse, explore and present data.

\begin{itemize}
\item
  Users can simply create useful summary of data and rearrange the
  information in any form with a few mouse clicks.
\item
  Pivot tables can create frequency distributions and
  cross-tabulations of several different data dimensions.
\item
  The users can also create \textbf{pivot charts} based on pivot tables,
  which provide meaningful, graphical data representation.
\end{itemize}

The following examples illustrate how to create pivot tables in Excel.
The dataset used in the examples contains data on sales from a
superstore The information on this data includes

\begin{itemize}
\item
  Order and ship dates,
\item
  Ship modes,
\item
  Customer details,
\item
  Product details,
\item
  Sale and profit amounts.
\end{itemize}

The file can be downloaded from
\url{https://community.tableau.com/docs/DOC-1236}.

\hypertarget{example-1}{%
\paragraph*{Example 1}\label{example-1}}
\addcontentsline{toc}{paragraph}{Example 1}

Suppose that the manager is interested in profits, broken down by region
and sub-category. Instead of sorting the data and creating formulas to
answer the question, you can summarise the data by creating a pivot
table, which can be done in the following steps:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  Select any cell or table containing the data.
\item
  From the \textbf{Insert} tab and click \textbf{PivotTable}.
\item
  Specify the data and location for the pivot table in the
  \textbf{PivotTable dialog box}.
\item
  A blank \textbf{PivotTable} and \textbf{PivotTable Fields List} will appear.
\item
  Drag the field names (or column headers) at the top to one of the
  four boxes at the bottom of the \textbf{PivotTable Fields List}.

  For this example,

  \begin{itemize}
  \item
    \textbf{Drag the Profit field into the Values area}. At this point,
    the pivot table displays the total of all the values in the
    Profit column.
  \item
    \textbf{Drag the Sub-Category field into the Row Labels area}. The
    pivot table shows the total profit for each of the sub
    categories.
  \item
    \textbf{Drag the Region field into the Column Labels area}. The pivot
    table shows the total profit for each of the sub categories,
    cross-tabulated by region.
  \end{itemize}
\item
  The pivot table will calculate and summarise the selected fields.
  The result is shown in the Table \protect\hyperlink{Table1}{1}.
\end{enumerate}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  The pivot table automatically updates the table with every change
  you make in the PivotTable Field List.
\item
  You can sort data in a PivotTable. Just right-click any cell in the
  column to sort and choose Sort from the short-cut menu.
\item
  You can apply number formatting, for example changing the Number
  Format to Currency.
\item
  Pivot table data is usually summarised using a sum. You can also
  summarise your data using different summary techniques, such as Sum,
  Count, Average, etc.
\end{enumerate}

\hypertarget{Table1}{}
\begin{longtable}[]{@{}crllll@{}}
\caption{Table 1: The pivot table from Example 1.}\tabularnewline
\toprule
Sum of Profit & Region & & & & \\
\midrule
\endfirsthead
\toprule
Sum of Profit & Region & & & & \\
\midrule
\endhead
Sub-Category & Central & East & South & West & Grand Total \\
Accessories & 7251.63 & 11195.86 & 7004.54 & 16484.6 & 41936.64 \\
Appliances & -2638.62 & 8391.41 & 4123.94 & 8261.27 & 18138.01 \\
Art & 1195.16 & 1899.94 & 1058.59 & 2374.1 & 6527.79 \\
Binders & -1043.64 & 11267.93 & 3900.66 & 16096.8 & 30221.76 \\
Bookcases & -1997.9 & -1167.63 & 1339.49 & -1646.51 & -3472.56 \\
Chairs & 6592.72 & 9357.77 & 6612.09 & 4027.58 & 26590.17 \\
Copiers & 15608.84 & 17022.84 & 3658.91 & 19327.24 & 55617.82 \\
Envelopes & 1777.53 & 1812.41 & 1465.48 & 1908.76 & 6964.18 \\
Fasteners & 236.62 & 263.99 & 173.72 & 275.19 & 949.52 \\
Furnishings & -3906.22 & 5881.41 & 3442.68 & 7641.27 & 13059.14 \\
Labels & 1073.08 & 1129.28 & 1040.77 & 2303.12 & 5546.25 \\
Machines & -1486.07 & 6928.64 & -1438.89 & -618.93 & 3384.76 \\
Paper & 6971.9 & 9015.37 & 5947.06 & 12119.24 & 34053.57 \\
Phones & 12323.03 & 12314.69 & 10767.28 & 9110.74 & 44515.73 \\
Storage & 1969.84 & 8389.37 & 2274.3 & 8645.32 & 21278.83 \\
Supplies & -661.89 & -1155.14 & 1.88 & 626.05 & -1189.1 \\
Tables & -3559.65 & -11025.38 & -4623.06 & 1482.61 & -17725.48 \\
Grand Total & 39706.36 & 91522.78 & 46749.43 & 108418.45 & 286397.02 \\
\bottomrule
\end{longtable}

\hypertarget{filters}{%
\subsection{Filters}\label{filters}}

Filters can be used to display part of your data that you need. For
example, you can determine how various discount rates affect the
profits.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  Drag a field to the \textbf{Filters} section. In this example, we will
  use Discount field.
\item
  The \textbf{filter} will appear above the pivot table. Then use a
  drop-down list to filter the displayed data by one or more items.
\end{enumerate}

The pivot table filltered by discount field is shown in Table
\protect\hyperlink{Table2}{2}.

\hypertarget{Table2}{}
\begin{longtable}[]{@{}crllll@{}}
\caption{Table 2: The pivot table is filtered by discount.}\tabularnewline
\toprule
Discount & 0.5 & & & & \\
\midrule
\endfirsthead
\toprule
Discount & 0.5 & & & & \\
\midrule
\endhead
Sum of Profit & Region & & & & \\
Sub-Category & Central & East & South & West & Grand Total \\
Bookcases & & -4255.81 & & & -4255.81 \\
Machines & & & -7635.23 & & -7635.23 \\
Tables & -4309.74 & & & -4305.64 & -8615.39 \\
Grand Total & -4309.74 & -4255.81 & -7635.23 & -4305.64 & -20506.43 \\
\bottomrule
\end{longtable}

\hypertarget{modifying-the-pivot-table}{%
\subsection{Modifying the pivot table}\label{modifying-the-pivot-table}}

You can add further summary information by using the \textbf{PivotTable Fields
List}. For example, you can add a second field (category) to the Row
Label area. Here you also need to change the order in which the fields
are listed, i.e.~Category should be on the top level followed by
sub-category. Table \protect\hyperlink{Table3}{3} shows the pivot table when two fields are added in
row labels.

\hypertarget{Table3}{}
\begin{longtable}[]{@{}clrllll@{}}
\caption{Table 3: Two fields are used for row labels.}\tabularnewline
\toprule
Sum of Profit & & Region & & & & \\
\midrule
\endfirsthead
\toprule
Sum of Profit & & Region & & & & \\
\midrule
\endhead
Category & Sub-Category & Central & East & South & West & Grand Total \\
Furniture & Bookcases & -1997.9 & -1167.63 & 1339.49 & -1646.51 & -3472.56 \\
& Chairs & 6592.72 & 9357.77 & 6612.09 & 4027.58 & 26590.17 \\
& Furnishings & -3906.22 & 5881.41 & 3442.68 & 7641.27 & 13059.14 \\
& Tables & -3559.65 & -11025.38 & -4623.06 & 1482.61 & -17725.48 \\
Furniture Total & & -2871.05 & 3046.17 & 6771.21 & 11504.95 & 18451.27 \\
Office Supplies & Appliances & -2638.62 & 8391.41 & 4123.94 & 8261.27 & 18138.01 \\
& Art & 1195.16 & 1899.94 & 1058.59 & 2374.1 & 6527.79 \\
& Binders & -1043.64 & 11267.93 & 3900.66 & 16096.8 & 30221.76 \\
& Envelopes & 1777.53 & 1812.41 & 1465.48 & 1908.76 & 6964.18 \\
& Fasteners & 236.62 & 263.99 & 173.72 & 275.19 & 949.52 \\
& Labels & 1073.08 & 1129.28 & 1040.77 & 2303.12 & 5546.25 \\
& Paper & 6971.9 & 9015.37 & 5947.06 & 12119.24 & 34053.57 \\
& Storage & 1969.84 & 8389.37 & 2274.3 & 8645.32 & 21278.83 \\
& Supplies & -661.89 & -1155.14 & 1.88 & 626.05 & -1189.1 \\
Office Supplies Total & & 8879.98 & 41014.58 & 19986.39 & 52609.85 & 122490.8 \\
Technology & Accessories & 7251.63 & 11195.86 & 7004.54 & 16484.6 & 41936.64 \\
& Copiers & 15608.84 & 17022.84 & 3658.91 & 19327.24 & 55617.82 \\
& Machines & -1486.07 & 6928.64 & -1438.89 & -618.93 & 3384.76 \\
& Phones & 12323.03 & 12314.69 & 10767.28 & 9110.74 & 44515.73 \\
Technology Total & & 33697.43 & 47462.04 & 19991.83 & 44303.65 & 145454.95 \\
Grand Total & & 39706.36 & 91522.78 & 46749.43 & 108418.45 & 286397.02 \\
\bottomrule
\end{longtable}

\hypertarget{example-2}{%
\paragraph*{Example 2}\label{example-2}}
\addcontentsline{toc}{paragraph}{Example 2}

Create a pivot table to answer the following questions

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  What are the total sales obtained from the top 5 customer who have
  spent the most, broken down by sub-category? How many orders did
  each customer have for each product?
\item
  How does the sales in the Central region compared with the other
  regions combined?
\item
  In which region does the superstore obtain the highest profit for
  each year?
\item
  Create a frequency distribution of the profit, filtered by year.
\end{enumerate}

\hypertarget{working-with-nonnumeric-data}{%
\subsection{Working with Nonnumeric Data}\label{working-with-nonnumeric-data}}

Pivot tables can be used for nonnumeric data. In this case, a useful
pivot table can be created that counts the items rather than sums of
them.

The following Pivot table cross-tabulates the segment for each
combination of segment and region. Here, we specify each of the Pivot
table fields as follows:

\begin{itemize}
\item
  The Segment field is used for the Columns.
\item
  The Region field is used for the Rows.
\item
  The Segment field is also used for the Values and is summarised by
  Count.
\item
  A second instance of the Segment field is added to the Values
  section. To display percentages, in Field Setting, choose Show
  Values As Percent of Column Total.
\end{itemize}

width=1

\begin{longtable}[]{@{}lllllllll@{}}
\caption{Table 4: The Pivot Table for Nonnumeric Data}\tabularnewline
\toprule
& Segment & & & & & & & \\
\midrule
\endfirsthead
\toprule
& Segment & & & & & & & \\
\midrule
\endhead
& Consumer & & Corporate & & Home Office & & Total Count & Total Percentage \\
& Count of Segment & Count of Segment by Percentage & Count of Segment & Count of Segment by Percentage & Count of Segment & Count of Segment by Percentage & & \\
Central & 1212 & 23.35\% & 673 & 22.28\% & 438 & 24.57\% & 2323 & 23.24\% \\
East & 1469 & 28.30\% & 877 & 29.04\% & 502 & 28.15\% & 2848 & 28.50\% \\
South & 838 & 16.14\% & 510 & 16.89\% & 272 & 15.26\% & 1620 & 16.21\% \\
West & 1672 & 32.21\% & 960 & 31.79\% & 571 & 32.02\% & 3203 & 32.05\% \\
Grand Total & 5191 & 100.00\% & 3020 & 100.00\% & 1783 & 100.00\% & 9994 & 100.00\% \\
\bottomrule
\end{longtable}

\hypertarget{bonds-and-inflation}{%
\section{Bonds and Inflation}\label{bonds-and-inflation}}

\hypertarget{zero-coupon-bonds}{%
\subsection{Zero-Coupon Bonds}\label{zero-coupon-bonds}}

The simplest type of bond is the one without coupons. Such bonds are
referred to as \textbf{zero-coupon bonds}. More precisely,

An \textbf{\(n\)-year zero-coupon bond} is a fixed interest security, redeemed
at par with term \(n\) and no coupon payments.

\begin{example}
\protect\hypertarget{exm:unlabeled-div-13}{}\label{exm:unlabeled-div-13}

\emph{What cash flows will an investor receive if the investor
holds an \(n\)-year zero-coupon per 100 THB face value until maturity? (Here
we let \(P_n\) denote the price now of the \(n\)-year zero-coupon)}

\end{example}

\begin{figure}

{\centering \includegraphics{SCMA329ExcelBookdownproj_files/figure-latex/tikz-bond-1} 

}

\caption{cashflows of a zero-coupon bond}\label{fig:tikz-bond}
\end{figure}

To calculate the rate of return of buying a bond and holding it until
maturity, it is simply the discount rate that equate the present value
of the investment to its costs (or bond price). Recall that \(P_n\)
denotes the price now of the \(n\)-year zero-coupon with FV face value and
\(y_n\) is the \textbf{yield to maturity}. The yield to maturity satisfies the
following equation \[\begin{aligned}
    P_n = \frac{FV}{(1+y_n)^n}.\end{aligned}\] Hence,
\[y_n = \left(\frac{FV}{P_n}\right)^{1/n} - 1.\]

\begin{example}
\protect\hypertarget{exm:yieldCurve}{}\label{exm:yieldCurve}

\emph{(Excel) Download the yields to maturity of zero-coupon
bonds per THB 100 face value with the terms ranging from 0.08 to 47
years from the following website (as of 11/03/2020)}

\emph{\url{http://www.thaibma.or.th/EN/Market/YieldCurve/Zero.aspx}}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  \emph{Using the zero-coupon rates provided from the given website, plot
  the interest rates (i.e.~yield to maturity) as a function of their
  maturities at any point in time. Give a brief explanation regarding
  to the shape of the plot.}
\item
  \emph{Determine the price now of the zero-coupon bond corresponding to
  the given yields to maturity.}
\end{enumerate}

\end{example}

\textbf{Notes}
1. We will often refer to the yield to maturity of the appropriate
maturity, zero-coupon risk-free bond as the \textbf{risk-free interest
rate}.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{1}
\item
  The term \textbf{spot interest rate} is also used to refer to these
  risk-free interest rate.
\item
  All \(n\)-year risk-free investments must earn the same return as the
  risk-free interest rate.
\item
  The plot in Example \ref{exm:yieldCurve} is known as the \textbf{yield curve}, which plots
  the risk-free interest rate for different maturities.
\item
  The yield curve is also called the \textbf{term structure of interest
  rates}.
\item
  Yield curves very from day to day, and could be increasing, or
  decreasing in shape, or even humped, depending on market
  expectations.
\end{enumerate}

\hypertarget{bond-pricing-using-yield-to-maturity}{%
\subsection{Bond pricing using yield to maturity}\label{bond-pricing-using-yield-to-maturity}}

Recall that a tax-exempt investor receives the full amount of the coupon
and redemption payments. The price of an \(n\) year fixed interest bond
which pays coupons of \(D\) per annum payable \(p\) thly in arrears and has
redemption amount \(R\) is \[P = D a_{\angln}^{(p)} + R v^n\] at rate \(i\)
per annum.

In practice, we can calculate by using a suitable time period, for
example a period of half a year as shown in the previous examples. Then
the formula can be written as
\[P = \frac{D}{2} a_{\angl{2n}} + R v^{2n}\]

\begin{example}
\protect\hypertarget{exm:unlabeled-div-14}{}\label{exm:unlabeled-div-14}

\emph{(Excel) (Modified from Financial Modeling Using Excel
and VBA) The bond price is the present value of its expected future
cashflows discounted at a rate appropriate for its risk. There are five
key bond variables including price, redemption rate, coupon rate,
remaining life, and discount rate, and any four of them determine the
fifth. Add suitable spinners to the annual coupon rate and yield to
maturity so that you can study how these variables affect the price of a
bond. (Hint :
\url{https://support.office.com/en-us/article/add-a-scroll-bar-or-spin-button}}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  \emph{Create an Excel model to calculate the price of a bond given its
  yield to maturity, redemption rate, annual coupon rate, frequency of
  coupon payments, and remaining life (and also face value). Make all
  of these input variables so that a user can use the model to value
  any bond for which these data are available.}
\item
  \emph{Create a chart to show how the price of a bond grows or declines to
  redemption amount as it approaches maturity.}
\end{enumerate}

\end{example}

\begin{example}
\protect\hypertarget{exm:unlabeled-div-15}{}\label{exm:unlabeled-div-15}

\emph{Make a copy of your Excel worksheet for bond pricing
calculation. The Excel model can be used to investigate how the value of
a bond changes with changes in the values of the other variables.}

\emph{Use the spinner to change the yield to maturity from a value less than
the coupon rate to a value greater than the coupon rate to see how the
valuation curve changes. What conclusion can you make regarding the
change in the values of the bond in respect of the change of the yield
to maturity? Write your conclusion in cell D1.}

\end{example}

\begin{example}
\protect\hypertarget{exm:unlabeled-div-16}{}\label{exm:unlabeled-div-16}

\emph{Make a copy of your Excel worksheet for bond pricing
calculation. The Excel model can be used to investigate how the value of
a bond changes with changes in the values of the other variables.}

\emph{Change the coupon rate to zero for a zero-coupon bond and notice that
the longer the remaining life, the lower the price of the bond. Then use
the spinner to vary the yields to maturity to see how valuation curve
changes. What conclusion can you make regarding the changes occurring?
Write your conclusion in cell D1.}

\end{example}

\hypertarget{interest-rate-risk-and-bond-prices}{%
\subsection{Interest rate risk and bond prices}\label{interest-rate-risk-and-bond-prices}}

While the effect of time on bond prices is predictable, unpredictable
changes in interest rates will also affect bond prices. Further, bonds
with different characteristics will respond differently to changes in
interest rates---some bonds will react more strongly than others.

\begin{example}
\protect\hypertarget{exm:unlabeled-div-17}{}\label{exm:unlabeled-div-17}

\emph{Consider a 10-year coupon bond and a 30-year coupon
bond, both with 10\% annual coupons and redeemable at par.}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  \emph{By what percentage will the price of each bond change if its yield
  to maturity increases from 5\% to 6\%? Answer in cells D1 and D2
  respectively.}
\item
  \emph{Plot the values of the 10-year and 30-year coupon bonds as the
  function of yield to maturity. Which of the bonds is more sensitive
  to a change in the yield? Why?}
\end{enumerate}

\end{example}

\hypertarget{inflation}{%
\subsection{Inflation}\label{inflation}}

Create an Excel model to calculate the required quantities as given in
the following questions. Look for the sheet CPI containing the CPI index
from the Bureau of Trade and Economic Indices.

\begin{example}
\protect\hypertarget{exm:unlabeled-div-18}{}\label{exm:unlabeled-div-18}

\emph{A 5-year bond with nominal value of ฿100 was issued in
1/1/2013. The coupon rate was 8\% p.a. payable yearly in arrears. The
redemption was 100\% after 5 years. The bond was issued at 100\%.}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  \emph{Calculate the monetary yield to a non-tax paying investor.}
\item
  \emph{With reference to the monthly CPI, calculate the real yield to a
  non-tax paying investor.}
\item
  \emph{Assuming that over the period of the transaction the annual rate of
  inflation will be constant and equal to 3.01\%, calculate the
  investor?s real yield on the transaction.}
\end{enumerate}

\end{example}

\hypertarget{introducing-visual-basic}{%
\section{Introducing Visual Basic}\label{introducing-visual-basic}}

The notes are obtained from the textbook \textbf{"Excel VBA Programming For
Dummies"} written by \textbf{Michael Alexander and John Walkenbach}

A macro is a sequence of instructions that automates some aspect of
Excel so that you can work more efficiently and with fewer errors.

\begin{itemize}
\item
  Excel records your actions and converts them into a VBA macro.
\item
  When you execute this macro, Excel performs the actions again.
\item
  More advanced users, though, can write code that tells Excel to
  perform tasks that can't be recorded.
\end{itemize}

\hypertarget{components-of-vba-editor-vbe}{%
\subsection{Components of VBA editor (VBE)}\label{components-of-vba-editor-vbe}}

The VBE consists of many parts including

\begin{description}
\item[Project (Explorer) window]
displays a hierarchical list of the projects and all of the items
contained and referenced by each project.
\end{description}

If the project has any VBA modules, the project listing also shows a
\textbf{Modules node}. A project may also contain a node called
\textbf{Forms}, which contains UserForm objects (which hold custom dialog
boxes).

With the project window, you can also add and remove a VBA module,
export and import objects.

\begin{description}
\item[Properties window]
lists the properties for selected objects and their current
settings. You can change these properties at the time during which
you build an application in the development environment.
\item[Immediate window]
displays information resulting from debugging statements in your
code or from commands typed directly into the window.
\item[Locals window]
displays all of the declared variables in the current procedure and
their values.
\end{description}

\begin{example}
\protect\hypertarget{exm:unlabeled-div-19}{}\label{exm:unlabeled-div-19}

(Project (Explorer) window). \emph{In the VBE, select the
project, namely Book1 and}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  \emph{add a new VBA module,}
\item
  \emph{then remove the VBA module you have just created from the project.}
\end{enumerate}

\end{example}

\textbf{Note} User can also add a new UserForm (try it yourself). The
UserFrom will be discussed later.

\begin{example}
\protect\hypertarget{exm:unlabeled-div-20}{}\label{exm:unlabeled-div-20}

\emph{(Properties window) In workbook Book1, add at least 2
new worksheets into it.}

\emph{Then in the VBE, perform the following tasks in the project Book1 by
using the Properties window :}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  \emph{Select Sheet1 from the project Book1 and change the name of Sheet1
  to Sheet2. What are the obtained results?}
\item
  \emph{Change the visible property from -1 to 0 and observe the outputs.
  What will happen if the visible property value is set to be 2?}
\item
  \emph{Insert a new Module and rename it as MyFirstModule.}
\end{enumerate}

\end{example}

\hypertarget{two-types-of-vba-macros}{%
\subsection{Two Types of VBA Macros}\label{two-types-of-vba-macros}}

A VBA macro (also known as a VBA procedure) can be one of two types: a
Sub or a Function.

\begin{itemize}
\item
  VBA Sub procedures. You can think of a Sub procedure as a new
  command that either the user or another macro can execute.
\item
  VBA functions. A function always returns a single value (just as a
  worksheet function always returns a single value). A VBA function
  can be executed by other VBA procedures or used in worksheet
  formulas, just as you would use Excel's built-in worksheet
  functions.
\end{itemize}

\hypertarget{creating-vba-macros}{%
\subsection{Creating VBA Macros}\label{creating-vba-macros}}

Excel provides two ways to create macros:

\begin{itemize}
\item
  Turn on the macro recorder and record your actions. To start the
  macro recorder, choose

  Developer \(\rightarrow\) Code \(\rightarrow\) Record Macro
\item
  Enter the code directly into a VBA module. The easiest way to create
  a simple macro is to record your actions. To develop more complex
  macros, however, you have to enter the VBA code manually, or write a
  program. To save time, you can often combine recording with manual
  code entry.
\end{itemize}

\begin{example}
\protect\hypertarget{exm:unlabeled-div-21}{}\label{exm:unlabeled-div-21}

\emph{Write a simple macro which uses the VBA builtin MsgBox
function to display a message in a dialog box. Name it as MyFirstMacro.}

\end{example}

Here is a possible answer.

\begin{verbatim}
Sub MyFirstMacro()
    'This is my first macro.
MsgBox "This is my first macro"
End Sub
\end{verbatim}

The following procedure shows how to run a procedure from another
procedure.

\begin{example}
\protect\hypertarget{exm:unlabeled-div-22}{}\label{exm:unlabeled-div-22}

\emph{(Executing the procedure from another procedure) Enter
this new procedure (either above or below MyFirstMacro code, it makes no
difference) to execute a procedure from another procedure.}

\end{example}

\begin{verbatim}
Sub MySecondMacro()
    'Use the Call keyword to execute a procedure from another procedure.
    MyFirstMacro
End Sub
\end{verbatim}

\hypertarget{how-vba-works}{%
\subsection{How VBA works}\label{how-vba-works}}

A concise summary of how VBA works:

\begin{itemize}
\item
  You perform actions in VBA by writing (or recording) code in a VBA
  module sheet and then executing the macro in any one of various
  ways. VBA modules are stored in an Excel workbook, and a workbook
  can hold any number of VBA modules. To view or edit a VBA module,
  you must activate the VB Editor window. (Press Alt+F11 to toggle
  between Excel and the VB Editor window.)
\item
  A VBA module consists of procedures. A procedure is basically
  computer code that performs some action.
\item
  A VBA module also can store function procedures. A function
  procedure performs calculations and returns a single value. A
  function can be called from another VBA procedure or can even be
  used in a worksheet formula.
\item
  VBA manipulates objects. Excel provides more than 100 classes of
  objects that you can manipulate. Examples of objects include a
  workbook, a worksheet, a range on a worksheet, a chart, and a
  rectangle shape.
\item
  Objects are arranged in a hierarchy and can act as containers for
  other objects.

  For example,

  \begin{itemize}
  \item
    Excel itself is an object called Application, and it contains
    other objects, such as Workbook objects.
  \item
    The Workbook object can contain other objects, such as Worksheet
    objects and Chart objects.
  \item
    A Worksheet object can contain objects such as Range objects,
    PivotTable objects, and so on. The arrangement of all these
    objects is referred to as an object model.
  \end{itemize}
\item
  Objects that are alike form a collection. For example,

  \begin{itemize}
  \item
    the Worksheets collection consists of all worksheets in a
    particular workbook.
  \item
    The ChartObjects collection consists of all ChartObjects on a
    worksheet.
  \item
    Collections are objects in themselves.
  \end{itemize}
\item
  You refer to an object in your VBA code by specifying its position
  in the object hierarchy, using a period as a separator.

  For example, you can refer to a workbook named Book1.xlsx as

\begin{verbatim}
Application.Workbooks("Book1.xlsx")
\end{verbatim}

  This expression refers to the Book1.xlsx workbook in the Workbooks
  collection. The Workbooks collection is contained in the Application
  object (that is, Excel). Extending this to another level, you can
  refer to Sheet1 in Book1 as follows:

\begin{verbatim}
Application.Workbooks("Book1.xlsx").Worksheets("Sheet1")
\end{verbatim}

  You can take it to still another level and refer to a specific cell
  as follows:

\begin{verbatim}
Application.Workbooks("Book1.xlsx").Worksheets("Sheet1"). \_

    Range("A1")
\end{verbatim}
\item
  If you omit specific references, Excel uses the active objects.

  If Book1.xlsx is the active workbook, the preceding reference can be
  simplified as follows:

\begin{verbatim}
    Worksheets("Sheet1").Range("A1")
\end{verbatim}

  If you know that Sheet1 is the active sheet, you can simplify the
  reference even more:

\begin{verbatim}
    Range("A1")
\end{verbatim}
\item
  Objects have properties. A property can be thought of as a setting
  for an object. For example,

  \begin{itemize}
  \item
    a Range object has properties, such as Value and Address.
  \item
    A Chart object has properties such as HasTitle and Type.
  \end{itemize}

  You can use VBA both to determine object properties and to change
  them.
\item
  You refer to properties by combining the object with the property,
  separated by a period. For example, you can refer to the value in
  cell A1 on Sheet1 as follows:

\begin{verbatim}
    Worksheets("Sheet1").Range("A1").Value
\end{verbatim}
\item
  You can assign values to variables. To assign the value in cell A1
  on Sheet1 to a variable called Interest, use the following VBA
  statement:

\begin{verbatim}
    Interest = Worksheets("Sheet1").Range("A1").Value
\end{verbatim}
\item
  Objects have methods. A method is an action that is performed with
  the object. For example, one of the methods for a Range object is
  ClearContents. This method clears the contents of the range.
\item
  You specify methods by combining the object with the method,
  separated by a period. For example, to clear the contents of range
  A1:C12, use the following statement:

\begin{verbatim}
    Worksheets("Sheet1").Range("A1:C12").ClearContents
\end{verbatim}
\item
  VBA also includes all the constructs of modern programming
  languages, including variables, arrays, looping, and so on.
\end{itemize}

\hypertarget{essential-vba-language-elements}{%
\subsection{Essential VBA Language Elements}\label{essential-vba-language-elements}}

\hypertarget{working-with-variables}{%
\subsubsection{Working with Variables}\label{working-with-variables}}

VBA's main purpose is to manipulate data. VBA stores the data in your
computer's memory. Some data, such as worksheet ranges, resides in
objects. Other data is stored in variables that you create.

A variable is simply a named storage location in your computer's
memory that's used by a program. Here are examples of variables

\begin{verbatim}
x = 1
InterestRate = 0.025
FaceValue = 1000
DataEntered = False
x = x + 1
UserName = "Peter Rabbit"
Date_Started = #1/15/2015#
\end{verbatim}

\hypertarget{data-types-and-declaring-variables}{%
\subsubsection{Data types and declaring variables}\label{data-types-and-declaring-variables}}

In this section, you discover how to declare a variable as a certain
data type. A variable's scope determines which modules and procedures
can use the variable.

\hypertarget{data-types}{%
\paragraph{Data types}\label{data-types}}

A data type is the characteristic of a variable that determines what kind of data it can hold. Data types include numerical and non-numerical
as well as user-defined types and specific types of objects. For details
about the supported data types, storage sizes and ranges, please see

\url{https://docs.microsoft.com/en-us/office/vba/language/reference/user-interface-help/data-type-summary}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  Numeric Data Types are types of data that consist of numbers, which
  can be computed mathematically with various standard operators such
  as addition, subtraction, multiplication, division and more. Numeric
  data types include \textbf{Byte, Integer, Long, Single, Double, Currency
  and Decimal}.
\item
  Non-Numeric Data Types are data that cannot be manipulated
  mathematically using standard arithmetic operators. The non-numeric
  data comprises text or \textbf{string} data types, the \textbf{Date} data
  types, the \textbf{Boolean} data types that store only two values (true
  or false), \textbf{Object} data type and \textbf{Variant} data type.
\end{enumerate}

\textbf{Note} The \textbf{Variant} data type is the data type for all variables
that are not explicitly declared as some other type (using statements
such as Dim, Private, Public, or Static).

\hypertarget{procedure-level-variables}{%
\paragraph{Procedure-level variables}\label{procedure-level-variables}}

The lowest level of scope for a variable is at the procedure level. (A
procedure is either a Sub or a Function procedure.) Variables declared
with this scope can be used only in the procedure in which they're
declared. When the procedure ends, the variable no longer exists, and
Excel frees up its memory. If you execute the procedure again, the
variable comes back to life, but its previous value is lost.

The following example shows some procedure-only variables declared by
using Dim statements:

\begin{verbatim}
Sub declaringVariables()
    Dim x As Integer
    Dim First As Long
    Dim InterestRate As Single
    Dim IssueDate As Date
    Dim UserName As String
    Dim MyValue
    '... [The procedure's code goes here] ...
End Sub
\end{verbatim}

\textbf{Note}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  A declaration statement can be placed within a procedure to create a
  \textbf{procedure-level variable}. Or it may be placed at the top of a
  module, in the Declarations section, to create a \textbf{module-level
  variable}.
\item
  If a declaration statement is given within a procedure, the variable
  can be used only in that procedure. If the statement appears in the
  \textbf{Declarations section} of the module, the variable is available to
  all procedures within the module, but not to procedures in other
  modules in the project.
\end{enumerate}

You can declare several variables in one statement. To specify a data
type, you \textbf{must include the data type for each variable}.

The following statement declares intX, intY and intZ as integer.

\begin{verbatim}
Dim intX As Integer, intY As Integer, intZ As Integer
\end{verbatim}

However, the following statement declares intZ as integer, while intX,
intY are as Variant type.

\begin{verbatim}
Dim intX, intY, intZ As Integer
\end{verbatim}

\textbf{Note} VBA has three other keywords that are used to declare
variables: \textbf{Static, Public and Private}. For more details, follow from
the following link:

\url{https://docs.microsoft.com/en-us/office/vba/language/}
concepts/getting-started/declaring-variables

Recall that the Locals window is very useful when we want to display all
of the declared variables in the current procedure and their values.

\begin{example}
\protect\hypertarget{exm:unlabeled-div-23}{}\label{exm:unlabeled-div-23}

\emph{(Locals window) Place a cursor anyway in the
declaringVariables procedure. On the debug menu, click Step Into command
in the debug menu once. Report the outputs obtained from the Locals
window.}

\end{example}

\begin{example}
\protect\hypertarget{exm:unlabeled-div-24}{}\label{exm:unlabeled-div-24}

\emph{Copy the following code and paste it before any
procedures in a module. What happens if you run the procedure?}

\end{example}

\begin{verbatim}
Option Explicit

Sub WithOptionExplicit()
    Dim x As Integer
    x = 20
    y = 5
End Sub
\end{verbatim}

\textbf{Note} The \textbf{Option Explicit} statement is used at the module level
to force explicit declaration of all variables in that module. When this
statement is present, you will not be able to run your code if it
contains any undeclared variables.

\begin{example}
\protect\hypertarget{exm:unlabeled-div-25}{}\label{exm:unlabeled-div-25}

\emph{Procedure-level variables) Step into (by pressing F8)
the following macro to observe the values of the variables in the Locals
window. What are the values of \(x\) and \(y\) when the procedure is
completely run?}

\end{example}

\begin{verbatim}
Option Explicit

Sub VariableScope()
    Dim x As Integer
    Dim y As Integer
    x = x + 1
    y = y + 1
End Sub
\end{verbatim}

\textbf{Note} Variables declared at the procedure level are the most
efficient because VBA frees up the memory they use when the procedure
ends.

\hypertarget{module-level-variables}{%
\paragraph{Module-level variables}\label{module-level-variables}}

Sometimes, you want a variable to be available to all procedures in a
module. If so, just declare the variable (using Dim or Private) before
the module's first Sub or Function statement, outside any procedures.
You do this in the Declarations section, at the beginning of your
module. (This is also where the Option Explicit statement is located.)

\hypertarget{public-variables}{%
\paragraph{Public variables}\label{public-variables}}

If you need to make a variable available to all the procedures in all your VBA modules in a workbook, declare the variable at the module level
(in the Declarations section) by using the Public keyword. Here's an
example:

\begin{example}
\protect\hypertarget{exm:unlabeled-div-26}{}\label{exm:unlabeled-div-26}

\emph{(Public variables)}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  \emph{Run the first macro three times. What are the values of \(x\) and \(y\)
  when the procedure is completely run?}
\item
  \emph{Then run the second macro. Is the value of \(x\) available to the
  second macro and what is the output observed from the Message box?}
\end{enumerate}

\end{example}

\begin{verbatim}
Option Explicit
Public y As Integer


Sub VariableScope2()
    Dim x As Integer

    x = x + 1
    y = y + 1
    MsgBox "The value of y is " & y

End Sub

Sub yValue()
    MsgBox "The value of y is " & y
End Sub
\end{verbatim}

\hypertarget{working-with-constants}{%
\subsection{Working with constants}\label{working-with-constants}}

Sometimes you need to refer to a value or string that never changes. In such a case, you need a constant - a named element whose value doesn't change.

As shown in the following examples, you declare constants by using the
Const statement.

\begin{verbatim}
Const NumQuarters As Integer = 4
Const Rate = .0725, Period = 12
\end{verbatim}

\hypertarget{working-with-dates}{%
\subsection{Working with dates}\label{working-with-dates}}

In VBA, place dates and times between two hash marks, as shown in the
preceding examples.

\begin{verbatim}
Dim Today As Date
Dim StartTime As Date
Const FirstDay As Date = #1/1/2013#
Const Noon = #12:00:00#
\end{verbatim}

\hypertarget{working-with-arrays}{%
\subsection{Working with Arrays}\label{working-with-arrays}}

An array is a group of variables that share a common name. You refer to
a specific variable in the array by using the array name and an index
number in parentheses.

The following example shows how to declare an array of 100 integers:

\begin{verbatim}
Dim MyArray(1 To 100) As Integer
\end{verbatim}

When you declare an array, you can choose to specify only the upper
index. If you omit the lower index, VBA assumes that it's 0.
Therefore, both of the following statements declare the same 101-element
array:

\begin{verbatim}
Dim MyArray (0 To 100) As Integer
Dim MyArray (100) As Integer
\end{verbatim}

If you want VBA to assume that 1 (rather than 0) is the lower index for your arrays, include the following statement in the Declarations section of your module:

\begin{verbatim}
Option Base 1
\end{verbatim}

This statement forces VBA to use 1 as the first index number for arrays that declare only the upper index. If this statement is present, the following statements are identical, both declaring a 100-element array:

\begin{verbatim}
Dim MyArray (1 To 100) As Integer
Dim MyArray (100) As Integer
\end{verbatim}

\hypertarget{multidimensional-arrays}{%
\subsubsection{Multidimensional arrays}\label{multidimensional-arrays}}

The arrays created in the previous examples are all one-dimensional arrays. Think of one-dimensional arrays as a single line of values. Arrays you create in VBA can have as many as 60 dimensions - although
you rarely need more than two or three dimensions in an array. The following example declares an 81-integer array with two dimensions:

\begin{verbatim}
Dim MyArray (1 To 9, 1 To 9) As Integer
\end{verbatim}

You can think of this array as occupying a 9 x 9 matrix. To refer to a
specific element in this array, you need to specify two index numbers
(similar to its ``row'' and its ``column'' in the matrix). The
following example shows how you can assign a value to an element in this
array:

\begin{verbatim}
MyArray (3, 4)= 100
\end{verbatim}

\hypertarget{dynamic-arrays}{%
\subsubsection{Dynamic arrays}\label{dynamic-arrays}}

You can also create dynamic arrays. A dynamic array doesn't have a preset number of elements. Declare a dynamic array with an empty set of parentheses:

\begin{verbatim}
Dim MyArray () As Integer
\end{verbatim}

Before you can use this array, you must use the ReDim statement to tell VBA how many elements the array has. Usually, the number of elements in the array is determined while your code is running. You can use the ReDim statement any number of times, changing the array's size as often as needed. The following example demonstrates how to change the
number of elements in a dynamic array. It assumes that the NumElements variable contains a value, which your code calculated.

\begin{verbatim}
ReDim MyArray (1 To NumElements)
\end{verbatim}

When you redimension an array by using ReDim, you wipe out any values currently stored in the array elements. You can avoid destroying the old
values by using the Preserve keyword. The following example shows how you can preserve an array's values when you redimension the array:

\begin{verbatim}
ReDim Preserve MyArray(1 To NumElements)
\end{verbatim}

\hypertarget{working-with-range-objects}{%
\subsection{Working with Range Objects}\label{working-with-range-objects}}

A Range object represents a range contained in a Worksheet object. Range objects, like all other objects, have properties (which you can examine and sometimes change) and methods (which perform actions on the object).

When you refer to a Range object, the address is always surrounded by double quotes, like this:

\begin{verbatim}
Range("A1:C5")
\end{verbatim}

If the range consists of one cell, you still need the quotes:

\begin{verbatim}
Range("K9")
\end{verbatim}

A Range object can consist of one or more entire rows or columns. You can refer to an entire row (in this case, row 3) by using syntax like this:

\begin{verbatim}
Range("3:3")
\end{verbatim}

You can refer to an entire column (the fourth column in this example) like this:

\begin{verbatim}
Range("D:D")
\end{verbatim}

The following expression refers to a two-area noncontiguous range. Notice that a comma separates the two areas.

\begin{verbatim}
Range("A1:B8,D9:G16")
\end{verbatim}

\hypertarget{the-cells-property}{%
\subsection{The Cells property}\label{the-cells-property}}

Rather than use the VBA Range keyword, you can refer to a range via the Cells property.

The Cells property takes two arguments: a row number and a column number. Both of these arguments are numbers, even though we usually refer to columns by using letters. For example, the following expression
refers to cell C2 on Sheet2:

\begin{verbatim}
Worksheets("Sheet2").Cells(2, 3)
\end{verbatim}

You can also use the Cells property to refer to a multi-cell range. The following example demonstrates the syntax you use:

\begin{verbatim}
Range(Cells(1, 1), Cells(10, 8))
\end{verbatim}

This expression refers to an 80-cell range that extends from cell A1 (row 1, column 1) to cell H10 (row 10, column 8). The following statements both produce the same result; they enter a value of 99 into a 10-by-8 range of cells. More specifically, these statements set the Value property of the Range object:

\begin{verbatim}
Range("A1:H10").Value = 99
Range(Cells(1, 1), Cells(10, 8)).Value = 99
\end{verbatim}

The advantage of using the Cells property to refer to ranges becomes apparent when you use variables rather than actual numbers as the Cells arguments. And things really start to click when you understand looping.

\hypertarget{the-offset-property}{%
\subsection{The Offset property}\label{the-offset-property}}

The Offset property provides another handy means for referring to ranges. This property, which operates on a Range object and returns another Range object, lets you refer to a cell that is a particular number of rows and columns away from another cell.

Like the Cells property, the Offset property takes two arguments. The first argument represents the number of rows to offset; the second represents the number of columns to offset.

The following expression refers to a cell one row below cell A1 and two columns to the right of cell A1. In other words, this refers to the cell commonly known as C2:

\begin{verbatim}
Range("A1").Offset(1, 2)
\end{verbatim}

The Offset property can also use negative arguments. A negative row offset refers to a row above the range. A negative column offset refers to a column to the left of the range. The following example refers to cell A1:

\begin{verbatim}
Range("C2").Offset(-1, -2)
\end{verbatim}

And, as you may expect, you can use 0 as one or both of the arguments for Offset. The following expression refers to cell A1:

\begin{verbatim}
Range("A1").Offset(0, 0)
\end{verbatim}

\hypertarget{some-useful-range-object-properties}{%
\subsection{Some Useful Range Object Properties}\label{some-useful-range-object-properties}}

The Value property The Value property represents the value contained in a cell. It's a read-write property, so your VBA code can either read
or change the value. The following statement displays a message box that
shows the value in cell A1 on Sheet1:

\begin{verbatim}
MsgBox Worksheets("Sheet1").Range("A1").Value
\end{verbatim}

It stands to reason that you can read the Value property only for a single-cell Range object. For example, the following statement generates
an error:

\begin{verbatim}
MsgBox Worksheets("Sheet1").Range("A1:C3").Value
\end{verbatim}

You can, however, change the Value property for a range of any size. The
following statement enters the number 123 into each cell in a range:

\begin{verbatim}
Worksheets("Sheet1").Range("A1:C3").Value = 123
\end{verbatim}

\hypertarget{the-text-property}{%
\subsection{The Text property}\label{the-text-property}}

The Text property returns a string that represents the text as it's displayed in a cell - the formatted value. The Text property is read-only. For example, suppose that cell A1 contains the value 12.3 and
is formatted to display two decimals and a dollar sign (\$12.30). The following statement displays a message box containing \$12.30:

\begin{verbatim}
MsgBox Worksheets("Sheet1").Range("A1").Text
\end{verbatim}

But the next statement displays a message box containing 12.3:

\begin{verbatim}
MsgBox Worksheets("Sheet1").Range("A1").Value
\end{verbatim}

If the cell contains a formula, the Text property returns the result of the formula. If a cell contains text, then the Text property and the
Value property will always return the same thing, because text (unlike a number) can't be formatted to display differently.

\hypertarget{the-count-property}{%
\subsection{The Count property}\label{the-count-property}}

The Count property returns the number of cells in a range. It counts all cells, not just the nonblank cells. Count is a read-only property, just as you would expect. The following statement accesses a range's Count property and displays the result (9) in a message box:

\begin{verbatim}
MsgBox Range("A1:C3").Count
\end{verbatim}

\hypertarget{the-column-and-row-properties}{%
\subsection{The Column and Row properties}\label{the-column-and-row-properties}}

The Column property returns the column number of a single-cell range. Its sidekick, the Row property, returns the row number of a single-cell range. Both are read-only properties. For example, the following
statement displays 6 because cell F3 is in the sixth column:

\begin{verbatim}
MsgBox Sheets("Sheet1").Range("F3").Column
\end{verbatim}

The next expression displays 3 because cell F3 is in the third row:

\begin{verbatim}
MsgBox Sheets("Sheet1").Range("F3").Row
\end{verbatim}

If the Range object consists of more than one cell, the Column property
returns the column number of the first column in the range, and the Row
property returns the row number of the first row in the range.

\hypertarget{the-address-property}{%
\subsection{The Address property}\label{the-address-property}}

Address, a read-only property, displays the cell address for a Range
object as an absolute reference (a dollar sign before the column letter
and before the row number).

\begin{verbatim}
MsgBox Range(Cells(1, 1), Cells(5, 5)).Address
\end{verbatim}

\hypertarget{the-formula-property}{%
\subsection{The Formula property}\label{the-formula-property}}

The Formula property represents the formula in a cell. This is a
read-write property, so you can access it to either view the formula in
a cell or insert a formula into a cell. For example, the following
statement enters a SUM formula into cell A13:

\begin{verbatim}
Range("A13").Formula = "=SUM(A1:A12)"
\end{verbatim}

Notice that the formula is a text string and is enclosed.

Here''s a statement that will enter a formula that contains quotes:

\begin{verbatim}
Range("A13").Formula = "=SUM(A1:A12)&"" Stores"""
\end{verbatim}

\hypertarget{the-numberformat-property}{%
\subsection{The NumberFormat property}\label{the-numberformat-property}}

The NumberFormat property represents the number format (expressed as a text string) of the Range object. This is a read-write property, so your
VBA code can either examine the number format or change it. The following statement changes the number format of column A to a percent with two decimal places:

\begin{verbatim}
Columns("A:A").NumberFormat = "0.00%"
\end{verbatim}

\hypertarget{some-useful-range-object-methods}{%
\subsection{Some Useful Range Object Methods}\label{some-useful-range-object-methods}}

As you know, a VBA method performs an action. A Range object has dozens of methods but, again, you won't need most of these. In this section,
I point out some of the more commonly used Range object methods. The
Select method Use the Select method to select a range of cells. The
following statement selects a range on the active worksheet:

\begin{verbatim}
Range("A1:C12").Select
\end{verbatim}

Before selecting a range, it''s often a good idea to use one additional statement to ensure that the correct worksheet is active. For example, if Sheet1 contains the range you want to select, use the following statements to select the range:

\begin{verbatim}
Sheets("Sheet1").Activate
Range("A1:C12").Select
\end{verbatim}

Contrary to what you may expect, the following statement generates an error if Sheet1 is not already the active sheet. In other words, you must use two statements rather than just one: one to activate the sheet and another to select the range.

\begin{verbatim}
Sheets("Sheet1").Range("A1:C12").Select
\end{verbatim}

If you use the GoTo method of the Application object to select a range, you can forget about selecting the correct worksheet first. This tatement activates Sheet1 and then selects the range:

\begin{verbatim}
Application.Goto Sheets("Sheet1").Range("A1:C12")
\end{verbatim}

The GoTo method is the VBA equivalent of pressing F5 in Excel, which displays the GoTo dialog box.

\hypertarget{the-copy-and-paste-methods}{%
\subsection{The Copy and Paste methods}\label{the-copy-and-paste-methods}}

You can perform copy and paste operations in VBA by using the Copy and Paste methods. Note that two different objects come into play. The Copy method is applicable to the Range object, but the Paste method applies to the Worksheet object. It actually makes sense: You copy a range and paste it to a worksheet. This short macro (courtesy of the macro recorder) copies range A1:A12 and pastes it to the same worksheet, beginning at cell C1:

\begin{verbatim}
Sub CopyRange()
    Range("A1:A12").Select
    Selection.Copy
    Range("C1").Select
    ActiveSheet.Paste
End Sub
\end{verbatim}

Notice that in the preceding example, the ActiveSheet object is used with the Paste method. This is a special version of the Worksheet object that refers to the currently active worksheet. Also notice that the macro selects the range before copying it. However, you don't have to select a range before doing something with it. In fact, the following
procedure accomplishes the same task as the preceding example by using a single statement:

\begin{verbatim}
Sub CopyRange2()
    Range("A1:A12").Copy Range("C1")
End Sub
\end{verbatim}

\hypertarget{the-clear-method}{%
\subsection{The Clear method}\label{the-clear-method}}

The Clear method deletes the contents of a range, plus all the cell
formatting. For example, if you want to zap everything in column D, the
following statement does the trick:

\begin{verbatim}
Columns("D:D").Clear
\end{verbatim}

\hypertarget{using-built-in-vba-functions}{%
\subsection{Using Built-In VBA Functions}\label{using-built-in-vba-functions}}

VBA provides numerous built-in functions. Some of these functions take
arguments, and some do not.

The first example uses VBA?s Date function to display the current system
date in a message box:

\begin{verbatim}
Sub ShowDate()
MsgBox "Today is: " & Date
End Sub
\end{verbatim}

The following procedure uses the VBA Len function, which returns the
length of a text string.

\begin{verbatim}
Sub GetLength()
Dim MyName As String
Dim StringLength As Long
MyName = Application.UserName
StringLength = Len(MyName)
MsgBox MyName & " has " & StringLength & " characters."
End Sub
\end{verbatim}

\hypertarget{discovering-vba-functions}{%
\subsection{Discovering VBA functions}\label{discovering-vba-functions}}

How do you find out which functions VBA provides? You can type VBA, followed by a period. You get a list of items. Those with a green icon
are functions. If this feature isn?t working, choose VBE's Tools -\textgreater{} Options, click the Editor tab, and place a check next to Auto List Members.

\hypertarget{using-worksheet-functions-in-vba}{%
\subsubsection{Using Worksheet Functions in VBA}\label{using-worksheet-functions-in-vba}}

Although VBA offers a decent assortment of built-in functions, you might not always find exactly what you need. Fortunately, you can also use most of Excel's worksheet functions in your VBA procedures. The only
worksheet functions that you cannot use are those that have an equivalent VBA function. VBA makes Excel's worksheet functions available through the WorksheetFunction object, which is contained in the Application object. Here's an example of how you can use Excel's SUM function in a VBA statement:

\begin{verbatim}
Total = Application.WorksheetFunction.Sum(Range("A1:A12"))
\end{verbatim}

You can omit the Application part or the WorksheetFunction part of the expression. In either case, VBA will figure out what you're doing. In
other words, these three expressions all work exactly the same:

\begin{verbatim}
Total = Application.WorksheetFunction.Sum(Range("A1:A12"))
Total = WorksheetFunction.Sum(Range("A1:A12"))
Total = Application.Sum(Range("A1:A12"))
\end{verbatim}

My personal preference is to use the WorksheetFunction part just to make
it perfectly clear that the code is using an Excel function.

\hypertarget{controlling-execution}{%
\subsection{Controlling execution}\label{controlling-execution}}

VBA uses many constructs that are found in most other programming
languages. These constructs are used to control the flow of execution.
This section introduces a few of the more common programming constructs.

\hypertarget{the-if-then-construct}{%
\subsubsection{The If-Then construct}\label{the-if-then-construct}}

One of the most important control structures in VBA is the If-Then construct, which gives your applications decision-making capability. The
basic syntax of the If-Then structure is as follows:

\begin{verbatim}
If condition Then statements [Else else statements]
\end{verbatim}

In plain English, if a condition is true, then a group of statement will
be executed. If you include the Else clause, then another group of
statements will be executed if the condition is not true.

This procedure checks the active cell. If it contains a negative value,
the cell's colour is changed to red. Otherwise, nothing happens.

\begin{verbatim}
Sub CheckCell()
If ActiveCell.Value < 0 Then ActiveCell.Font.ColorIndex = 3
End Sub
\end{verbatim}

\textbf{Note} See
\url{https://docs.microsoft.com/en-us/office/vba/api/excel.colorindex} for colorindex property.

\hypertarget{for-next-loops}{%
\subsubsection{For-Next loops}\label{for-next-loops}}

You can use a For-Next loop to execute one or more statements a number of times. Here's an example of a For-Next loop:

\begin{verbatim}
Sub SumSquared()
    Total = 0
    For Num = 1 To 10
        Total = Total + (Num ^ 2)
    Next Num
    MsgBox Total
End Sub
\end{verbatim}

\hypertarget{the-with-end-with-construct}{%
\subsubsection{The With-End With construct}\label{the-with-end-with-construct}}

Another construct that you encounter if you record macros is the With-End With construct. This is a useful when dealing with several
properties or methods of the same object. The following is an example:

\begin{verbatim}
Sub AlignCells()
    With Selection
        .HorizontalAlignment = xlCenter
        .VerticalAlignment = xlCenter
        .WrapText = False
        .Orientation = xlHorizontal
    End With
End Sub
\end{verbatim}

\hypertarget{the-select-case-construct}{%
\subsubsection{The Select Case construct}\label{the-select-case-construct}}

The Select Case construct is useful for choosing among two or more options. The following example demonstrates the use of a Select Case construct. In this example, the active cell is checked. If its value is
less than 0, it's coloured red. If it's equal to 0, it's coloured blue. If the value is greater than 0, it's coloured black.

\begin{verbatim}
Sub CheckCell()
    Select Case ActiveCell.Value
        Case Is < 0
            ActiveCell.Font.Color = vbRed
        Case 0
            ActiveCell.Font.Color = vbBlue
        Case Is > 0
            ActiveCell.Font.Color = vbBlack
        End Select
End Sub
\end{verbatim}

Any number of statements can go below each Case statement, and they all
get executed if the case is true.

\textbf{Note} See Color constants for example vbRed, vbBlue etc. for more
details:

\url{https://docs.microsoft.com/en-us/office/vba/language/reference/user-interface-help/color-constants}

\hypertarget{vba-examples}{%
\subsection{VBA Examples}\label{vba-examples}}

\begin{example}
\protect\hypertarget{exm:unlabeled-div-27}{}\label{exm:unlabeled-div-27}

\emph{The NumSign function uses the Select Case construct to
take a different action, depending on the value of num. If num is less
than 0, NumSign is assigned the text Negative. If num is equal to 0,
NumSign is Zero. If num is greater than 0, NumSign is Positive. The
value returned by a function is always assigned to the function's name.}

\end{example}

\begin{verbatim}
Function NumSign(num)
    Select Case num
        Case Is < 0
            NumSign = "Negative"
        Case 0
            NumSign = "Zero"
        Case Is > 0
            NumSign = "Positive"
        End Select
End Function
\end{verbatim}

If you work with this function, you might notice a problem if the argument is non-numeric. In such a case, the function returns Positive. In other words, the function has a bug. Following is a revised version that returns an empty string if the argument is non-numeric. This code uses the VBA IsNumeric function to check the argument. If it's numeric,
the code checks the sign. If the argument is not numeric, the Else part
of the If-Then-Else structure is executed.

\begin{verbatim}
Function NumSign(num)
    If IsNumeric(num) Then
        Select Case num
            Case Is < 0
                NumSign = "Negative"
            Case 0
                NumSign = "Zero"
            Case Is > 0
                NumSign = "Positive"
        End Select
    Else
        NumSign = ""
    End If
End Function
\end{verbatim}

\begin{example}
\protect\hypertarget{exm:unlabeled-div-28}{}\label{exm:unlabeled-div-28}

\emph{Create a macro that copies a variable-sized range (you
don't know the exact row and column dimension).}

\end{example}

The following macro demonstrates how to copy this range from Sheet1 to Sheet2 (beginning at cell A1). It uses the CurrentRegion property,
which returns a Range object that corresponds to the block of cells around a particular cell. In this case, that cell is A1.*

\begin{verbatim}
Sub CopyCurrentRegion()
    Range("A1").CurrentRegion.Copy
    Sheets("Sheet2").Select
    Range("A1").Select
    ActiveSheet.Paste
    Sheets("Sheet1").Select
    Application.CutCopyMode = False
End Sub
\end{verbatim}

You can make this macro even more efficient by not selecting the
destination. The following macro takes advantage of the fact that the
\textbf{Copy method can use an argument for the destination range}:

\begin{verbatim}
Sub CopyCurrentRegion2()
    Range("A1").CurrentRegion.Copy _
    Sheets("Sheet2").Range("A1")
End Sub
\end{verbatim}

It's even a bit easier if the data is in the form of a table (created in Excel using Insert \(\rightarrow\) Tables \(\rightarrow\) Table). The table has a name (such as Table1) and expands automatically when new data is
added.

\begin{verbatim}
Sub CopyTable()
    Range("Table1").Copy  Sheets("Sheet2").Range("A1")
End Sub
\end{verbatim}

\begin{example}
\protect\hypertarget{exm:unlabeled-div-29}{}\label{exm:unlabeled-div-29}

\emph{The following VBA procedure selects the range beginning
at the active cell and extending down to the cell just above the first
blank cell in the column. After selecting the range, you can do whatever
you want with it}

\end{example}

\begin{verbatim}
Sub SelectDown()
    Range(ActiveCell,ActiveCell.End(xlDown)).Select
End Sub
\end{verbatim}

This example uses the End method of the ActiveCell object, which returns
a Range object. The End method takes one argument, which can be any of
the following constants:

\begin{itemize}
\item
  xlUp
\item
  xlDown
\item
  xlToLeft
\item
  xlToRight
\end{itemize}

It is not necessary to select a range before doing something with it.
The following macro applies bold formatting to a variable-sized (single
column) range without selecting the range:

\begin{verbatim}
Sub MakeBold()
    Range(ActiveCell, ActiveCell.End(xlDown)) _
    .Font.Bold = True
End Sub
\end{verbatim}

\begin{example}
\protect\hypertarget{exm:unlabeled-div-30}{}\label{exm:unlabeled-div-30}

\emph{The following procedure demonstrates how to select the
column that contains the active cell. It uses the \textbf{EntireColumn
property, which returns a Range object that consists of a full
column}:}

\end{example}

\begin{verbatim}
Sub SelectColumn()
    ActiveCell.EntireColumn.Select
End Sub
\end{verbatim}

\begin{example}
\protect\hypertarget{exm:unlabeled-div-31}{}\label{exm:unlabeled-div-31}

\emph{Many macros perform an operation on each cell in a
range, or they might perform selected actions based on each cell's
content. These macros usually include a For-Next loop that processes
each cell in the range.}

\emph{The following example demonstrates how to loop through a range of
cells. In this case, the range is the current selection. An object
variable named Cell refers to the cell being processed. Within the For
Each-Next loop, the single statement evaluates the cell and applies bold
formatting if the cell contains a positive value.}

\end{example}

\begin{verbatim}
Sub ProcessCells()
    Dim Cell As Range
    For Each Cell In Selection
        If Cell.Value > 0 Then Cell.Font.Bold = True
    Next Cell
End Sub
\end{verbatim}

This example works, but what if the user's selection consists of an
entire column or row?

\begin{example}
\protect\hypertarget{exm:unlabeled-div-32}{}\label{exm:unlabeled-div-32}

(Prompting for a cell value) You can use VBA's
InputBox function to get a value from the user. Then you can insert
that value into a cell. The following procedure demonstrates how to ask the user for a value and place the value in cell A1 of the active
worksheet, using only one statement:

\end{example}

\begin{verbatim}
Sub GetValue()
    Range("A1").Value = InputBox( _
    "Enter the value for cell A1")
End Sub
\end{verbatim}

\textbf{Note} See
\url{https://docs.microsoft.com/en-us/office/vba/api/excel.application.inputbox}
for details about InputBox.

\begin{example}
\protect\hypertarget{exm:unlabeled-div-33}{}\label{exm:unlabeled-div-33}

\emph{Create a model with VBA to produce a (year-by-year)
loan schedule for a fixed rate loan. The loan is to be repaid in equal annual instalments over its life and the first payment is to be made at the end of the first year. Format the output data in the table with a dollar sign and two decimal points, i.e "\$\#,\#\#0.00".}

\end{example}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{tutorial-1}{%
\section{Tutorial 1}\label{tutorial-1}}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  Calculate the following accumulation:

  \begin{enumerate}
  \def\labelenumii{\arabic{enumii}.}
  \item
    Accumulate \$5,000 for 4 years at 7.5\% per annum effective.
  \item
    Accumulate \$800 for 2.7 years at 3\% per quarter-year effective.
  \item
    Accumulate \$10,000 for 27 months at 4.25\% per half-year
    effective.
  \end{enumerate}
\item
  Calculate the present values on 1 January 2015 of the following
  payments at the given rates of interest:

  \begin{enumerate}
  \def\labelenumii{\arabic{enumii}.}
  \item
    \$1,000 on 1 January 2016, at 7.5\% per annum effective.
  \item
    \$100 on 1 October 2016, at 3\% per quarter-year effective.
  \item
    \$10,000 on 1 April 2016, at 4.25\% per half-year effective.
  \end{enumerate}
\item
  \begin{enumerate}
  \def\labelenumii{\arabic{enumii}.}
  \item
    If the effective rate of interest is 4\% per annum, calculate the
    effective rate of interest per month?
  \item
    If the effective rate of interest is 6.5\% per half-year,
    calculate the effective rate of interest per quarter-year?
  \end{enumerate}
\item
  The effective rate of interest per annum was 4\% during 2015, 5\%
  during 2016 and 6\% thereafter.

  \begin{enumerate}
  \def\labelenumii{\arabic{enumii}.}
  \item
    Calculate the accumulation of \$500 from 1 January 2015 to 1
    January 2018.
  \item
    Calculate the accumulation of \$2000 from 1 April 2015 to 1
    October 2017.
  \item
    Calculate the accumulation factor from 1 January 2015 to 1
    January 2018.
  \end{enumerate}
\item
  You deposit \$ 3000 to an account that earn 2.5\% compounded
  annually. How much will you have in three years?
\item
  A person borrows a sum of \$5,000 and agrees to pay this back at the
  end of 1 year with interest calculated at an effective rate of 10\%
  per annum. Calculate the amount to be repaid for the loan.
\item
  You want to have \$1000 in 2 years and \$2000 in 4 years. How much
  should you deposit now into an account earning the effective rate of
  5.75\% semiannually?
\item
  Katy deposits 100 into a saving account which pays interest at \(i\)
  \textbf{per quarter} effective.

  At the same time, Taylor deposits 500 into a different saving
  account which pays a simple interest at an annual rate of \(i\).

  During the last 3 months of the 4th year, they both earn the same
  amount of interest. Calculate \(i\).
\item
  An ordinary annuity is a series of equal payments made at the end of
  consecutive periods over a fixed length of time. Draw a timeline for
  the following annuity having cashflow of 1 unit at the end of each
  of the next n time units.
\item
  Draw a timeline to illustrate this insurance benefit: Whole Life
  Insurance - payable immediately on death - has following conditions:

  \begin{itemize}
  \item
    death benefit (sum insured) of 1
  \item
    payable immediately on the death
  \item
    of an individual currently aged x
  \item
    for death occurring any time in the future.
  \end{itemize}
\item
  (Excel) It is a good exercise to check whether the Excel worksheet
  you have developed so far for calculating the present value and
  future value can be applied to the questions in this Tutorial. What
  would you do to improve the Excel worksheet that can be applied to a
  more general scenario?
\end{enumerate}

\hypertarget{tutorial-2}{%
\section{Tutorial 2}\label{tutorial-2}}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  Starting at 1 January 2015, the effective rate of interest per annum
  was 3\% per quarter-year for 9 months, 4\% per half-year for 15 months
  and and 2\% per month thereafter.

  \begin{enumerate}
  \def\labelenumii{\arabic{enumii}.}
  \item
    Calculate the accumulation factor from 1 January 2015 to 1
    January 2018.
  \item
    Calculate the accumulation of \$5,000 from 1 July 2015 to 1
    October 2017.
  \item
    Calculate the accumulation of \$100 from 1 March 2016 to 1
    August 2018.
  \item
    Calculate the present value at 1 January 2015 of \$ 25,000
    receivable on 1 July 2016.
  \item
    Calculate the present value at 1 April 2015 of \$ 8,000
    receivable on 1 October 2017.
  \item
    Calculate the discount factor from 1 July 2015 to 1
    October 2016.
  \end{enumerate}
\item
  The effective rate of interest is 7.25\% per time unit. Cashflows are
  shown in the following time line.

  \begin{enumerate}
  \def\labelenumii{\arabic{enumii}.}
  \item
    Calculate the accumulation at time time t = 4 units of these
    cashflows.
  \item
    Calculate the accumulation at time time t = 8 units of these
    cashflows.
  \item
    Calculate the present value at time time t = 0 units of these
    cashflows.
  \end{enumerate}
\end{enumerate}

\begin{center}\includegraphics{SCMA329ExcelBookdownproj_files/figure-latex/tikz-exam1-1} \end{center}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{2}
\item
  The effective rate of interest is 6\% per time unit. Cashflows are
  shown in the following time line.

  \begin{enumerate}
  \def\labelenumii{\arabic{enumii}.}
  \item
    Calculate the accumulation at time time t = 5 units of these
    cashflows.
  \item
    Calculate the value at time time t = 2 units of these cashflows.
  \item
    Calculate the present value at time time t = 0 units of these
    cashflows.
  \end{enumerate}
\end{enumerate}

\begin{center}\includegraphics{SCMA329ExcelBookdownproj_files/figure-latex/tikz-exam2-1} \end{center}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{3}
\item
  The effective rate of interest per annum was 4\% during 2015, 3\% per
  half-year until 1 October 2017 and 1.5\% per month thereafter.
  Cashflows are shown in the following time line.

  \begin{enumerate}
  \def\labelenumii{\arabic{enumii}.}
  \item
    Calculate the accumulation on 1/1/2019 of these cashflows.
  \item
    Calculate the present value on 1/1/2015 of these cashflows.
  \item
    Calculate the value at time time 1/7/2017 of these cashflows.
  \end{enumerate}
\end{enumerate}

\begin{center}\includegraphics{SCMA329ExcelBookdownproj_files/figure-latex/tikz-exam3-1} \end{center}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{4}
\tightlist
\item
  (Excel) It is a good exercise to check whether the Excel worksheet
  you have developed so far for calculating the present value and
  future value can be applied to the questions in this Tutorial. What
  would you do to improve the Excel worksheet for a more general
  scenario?
\end{enumerate}

\hypertarget{tutorial-3}{%
\section{Tutorial 3}\label{tutorial-3}}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  Calculate the present value now of an annuity payable monthly in
  advance. The annual amount of the annuity will be \$ 2,400 for the
  first 10 years and \$ 3,600 for the next 15 years, after which
  payment will cease. Assume that the effective rate of interest is 2\%
  per annum.
\item
  Assume that the effective rate of interest will be 3\% for 5 years
  from now, 4\% for the next 5 years and 5\% thereafter. Calculate the
  following values:

  \begin{enumerate}
  \def\labelenumii{\arabic{enumii}.}
  \item
    The present value of an annuity of \$ 1,000 per annum, payable
    in arrear for 15 years.
  \item
    The present value of an annuity due of \$ 500 per annum, payable
    at the beginning of the year for 20 years.
  \item
    The accumulation value of an increasing annuity payable yearly
    in arrear for 30 years. The first annual payment is \$ 100, and
    payments will be increase by \$ 100 each year.
  \item
    The accumulation value of an increasing annuity payable yearly
    in advance for 18 years. The first annual payment is \$ 1,000,
    and payments will be increase by 2\% each year (compound).
  \item
    The present value of an annuity of \$ 200, payable in arrear for
    10 years and deferred for 3 years.
  \end{enumerate}
\item
  You borrow \$ 240,000 from a bank to be repaid by the end of 5
  years. Assume that the interest rate is 4\% per annum. Consider the
  following four possible options for the loan to be repaid.

  \begin{enumerate}
  \def\labelenumii{\arabic{enumii}.}
  \item
    Calculate the amount of the repayments to repay if you choose to
    repay the loan as late as possible.
  \item
    You may choose to repay interest only during the 5 years term of
    loan and repay the capital at the end of the term. Calculate
    interest to be repaid and draw the timeline to illustrate the
    cashflows for the repayment of the loan.
  \item
    Calculate the amount X of level instalments to repay the loan
    which will be paid at the end of each year for 5 years and draw
    the timeline to illustrate the cashflows for the repayment of
    the loan.
  \item
    Calculate the amount Y of level instalments to repay the loan
    which will be paid at the end of each month for 5 years and draw
    the timeline to illustrate the cashflows for the repayment of
    the loan. \textbf{Instalment} is a sum of money due as one of several
    equal payments for something, spread over an agreed period of
    time.
  \end{enumerate}
\item
  A person now age 30 has received a pension from a company. When he
  retires at age 60, he will be paid on each birthday from the 60 to
  the 85th inclusive. The first annual payment will be half of his
  salary when he retires, and payments will then increase by 2\%
  compounding each year. Currently, he receive a salary of \$ 20,000
  and will increase by 3\% each year compounding in line with
  inflation. Assume that the effective rate of interest will be 4\% for
  the next 20 years and 5\% thereafter. Calculate the present value now
  of this pension.
\item
  (Excel) Use Excel worksheet you have developed so far to calculate
  the results from the questions in this Tutorial.
\end{enumerate}

\hypertarget{tutorial-4}{%
\section{Tutorial 4}\label{tutorial-4}}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  Show that the following series of cashflows are equivalent given
  that an interest rate is 4\% per annum effective.

  \begin{enumerate}
  \def\labelenumii{\arabic{enumii}.}
  \item
    One single payment of amount 14,802.44 at year 10.
  \item
    a level annuity of 400 payable yearly in arrear for the next 10
    years plus a lump sum of 10,000.
  \item
    a level annuity of 1,232.91 payable yearly in arrear for the
    next 10 years.
  \end{enumerate}
\item
  You invest in a project which requires you to pay 2,000 and receive
  back 300 at the end of each of the next 8 years. Calculate the yield
  of this investment. ANS = 4.2394551\%
\item
  You pay a price of 5,000 for an investment that will repay you 600
  per annum payable half-yearly in arrear for the next 12 years.
  Calculate the yield of this investment. ANS = 3.1491266\%
\item
  An investor pays 100,000 in order to receive 20,000 back at the end
  of the first 3 years and 25,000 back at the end in the next 4 years.
  Calculate the yield of this investment. ANS = 12.6209232\%
\item
  You invest in a project which requires you to pay 500,000 at the
  start of each of the calendar years 2018, 2019 and 2020. The project
  is expected to return profits of 400,000 for 6 years a the end of
  each calendar year 2024 to 2029 inclusive. Calculate the yield of
  this investment. ANS = 5.7285486\%
\item
  (Modified from CT1 2012 IFoA Exam)

  An investor is considering two projects, Project A and Project B.
  Project A involves the investment of 2,000,000 in a retail outlet.
  Rent is received quarterly in arrear for 25 years, at an initial
  rate of 100,000 per annum. It is assumed that the rent will increase
  at a rate of 5\% per annum compound, but with increases taking place
  every five years. Maintenance and other expenses are incurred
  quarterly in arrear, at a rate of 12,000 per annum. The retail
  outlet reverts to its original owner after 25 years for no payment.

  Project B involves the purchase of an office building for 1,000,000.
  The rent is to be received quarterly in advance at an initial rate
  of 85,000 per annum. It is assumed that the rent will increase to
  90,000 per annum after 20 years. There are no maintenance or other
  expenses. After 25 years the property reverts to its original owner
  for no payment.

  Calculate the annual effective internal rate of return for both
  Projects A and B. Which project is preferable?
\item
  (Excel) Use Excel worksheet you have developed to calculate the
  results from the questions in this Tutorial.
\end{enumerate}

\hypertarget{tutorial-5}{%
\section{Tutorial 5}\label{tutorial-5}}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  You borrow 30,000 for a term of 6 months to be repaid in arrear by
  level monthly instalments. The rate of interest will be 4\% pa
  effective.

  \begin{enumerate}
  \def\labelenumii{\arabic{enumii}.}
  \item
    Calculate the monthly repayment.
  \item
    Construct the complete loan schedule
  \end{enumerate}
\item
  A loan of 800,000 is repayable by equal monthly repayments for 10
  years, with interest rate payable at 6.5\% pa effective.

  \begin{enumerate}
  \def\labelenumii{\arabic{enumii}.}
  \item
    Calculate the amount of each monthly payment.
  \item
    Calculate the interest and capital contents of the 96th
    repayment.
  \end{enumerate}
\item
  \begin{enumerate}
  \def\labelenumii{\arabic{enumii}.}
  \item
    An investor takes out a loan of 100,000 from a bank to be repaid
    by level annual instalments in arrear over 12 years where the
    bank charges an effective annual rate of interest of 7\%.
    Immediately after the 6th repayment has been made, the investor
    may

    \begin{enumerate}
    \def\labelenumiii{\arabic{enumiii}.}
    \item
      extend the term of the loan by extra 2 year, or
    \item
      miss the next two repayments.
    \end{enumerate}

    Calculate the revised repayment amount in each case.
  \item
    Suppose the bank allows the
    investor to miss the next two repayments but the capital
    outstanding will be charged interest at 10\% pa effective while
    the investor is not making repayments. Calculate the revised
    repayment.
  \item
    Suppose in Question 3.2 that the investor will miss the next two
    repayment and extend the term of the loan by extra 4 years.
    Calculate the revised repayment.
  \end{enumerate}
\item
  An investor borrows 50,000 for a term of 12 years. The rate of
  interest will be 4\% pa effective for the first 6 years and 5\% pa
  effective thereafter. The loan will be repaid level annual
  repayments for the first 6 years, and then increasing to twice the
  origin level for the last 6 years. Calculate the annual repayment.
\item
  An investor borrows 40,000 for a term of 10 years. The rate of
  interest will be 6.5\% pa effective The loan will be repaid level
  annual repayments, increasing at 2\% per annum.

  \begin{enumerate}
  \def\labelenumii{\arabic{enumii}.}
  \item
    Calculate the first annual repayment.
  \item
    Calculate the capital outstanding after the 7th repayment is
    made.
  \item
    Calculate the interest content of the 8th repayment.
  \end{enumerate}
\item
  (Excel) Suppose you borrow \(L\) from a bank to be repaid by the end
  of \(n\) years at an interest rate of \(i\%\) per annum effective. If
  you agree to repay the loan and the interest in equal annual
  instalments throughout term of loan and the first payment is made at
  the end of the first year.

  Create a model to produce a loan amortisation (or loan schedule)
  table. Make the interest rate, loan life, initial loan, and other
  necessary variables input variables. The loan amortisation table
  should include the following columns:

  \begin{itemize}
  \item
    The year-beginning balance
  \item
    The annual repayment
  \item
    Interest Component
  \item
    Capital content
  \item
    Capital outstanding (the year-end balance)
  \end{itemize}
\end{enumerate}

\hypertarget{solutions-to-tutorial-1}{%
\section{Solutions to Tutorial 1}\label{solutions-to-tutorial-1}}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  The solutions to each question are as follows:

  \begin{enumerate}
  \def\labelenumii{\arabic{enumii}.}
  \tightlist
  \item
    \(5000 (1.075)^4 = 6677.345703\)
  \item
    Let \(i\%\) be the annual rate effective equivalent to \(3\%\) per quarter-effective, \(i = (1.03)^4 - 1\).
    Hence, the accumulation is
    \[800(1+i)^{2.7} = 800(1.03)^{4\times2.7} = 1100.859802.\]
  \item
    Let \(j\%\) be the monthly rate effective equivalent to \(4.25\%\) per half-year effective, \(j = (1.0425)^{2/12} - 1\).
    Hence, the accumulation is
    \[10000(1.0425)^{(2/12)\times27} = 12059.86056.\]
  \end{enumerate}
\item
  The solutions to each question are as follows:

  \begin{enumerate}
  \def\labelenumii{\arabic{enumii}.}
  \tightlist
  \item
    \(\frac{1000}{1.075} = 930.232558\).
  \item
    \(\frac{100}{(1.03)^7} = 81.309151\).
  \item
    Let \(j\%\) be the quarterly rate effective equivalent to \(4.25\%\) per half-year effective, \(j = (1.0425)^{2/4} - 1\).
    Hence, the present value is
    \[10000\times (1+j)^{-5} = 10000(1.0425)^{-(5/2)} = 9011.764643.\]
  \end{enumerate}
\item
  The solutions to each question are as follows:

  \begin{enumerate}
  \def\labelenumii{\arabic{enumii}.}
  \tightlist
  \item
    0.3274\%
  \item
    3.1988\%
  \end{enumerate}
\item
  The solutions to each question are as follows:

  \begin{enumerate}
  \def\labelenumii{\arabic{enumii}.}
  \tightlist
  \item
    500(1.04)(1.05)(1.06) =578.76
  \item
    \(2000(1.04)^{3/4}(1.05)(1.06)^{3/4} =2259.299\)
  \item
    (1.04)(1.05)(1.06) = 1.15752
  \end{enumerate}
\item
  The account balance in 3 years is \(3000(1.025)^{3} = 3230.67\).
\item
  The amount to be repaid for the loan is 5000(1.1) = 5500.
\item
  Let \(X\) be the amount to be deposited now.
  \[X = \frac{1000}{(1.0575)^4} + \frac{2000}{(1.0575)^8} = 2078.36. \]
\item
  At time 3.75 years, Katy has a balance of \(100(1+i)^{15}\). The interest on this balance over the next 3 months is \(100(1+i)^{15}\cdot i\).
  Taylor earns simple interest on the original amount which is equal to \(500i\cdot\frac{3}{12}\). Therefore, we solve for \(i\) from the following equation:
  \[ 100(1+i)^{15}\cdot i = 500i\cdot\frac{3}{12},\] which gives \(i = 0.014987.\)
\item
  The timeline for the following annuity having cashflow of 1 unit at the end of each of the next \(n\) time units is given in the figure below:
\end{enumerate}

\begin{center}\includegraphics{SCMA329ExcelBookdownproj_files/figure-latex/tikz-sol1-1} \end{center}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{9}
\tightlist
\item
  (More details in the course ``Life Contingencies I''). We need to define a random variable \(T_x\) = the remaining future life time of a life aged \(x\).
\end{enumerate}

\begin{center}\includegraphics{SCMA329ExcelBookdownproj_files/figure-latex/tikz-sol2-1} \end{center}

The quantity of interest is the present value of the death benefit assuming the interest rate of \(i\%\) p.a. effective. It is also a random variable,
\[PV = \frac{1}{(1+i)^{T_x}}.\] It turns out that the premium rate of this whole life insurance is \(E[PV]\), the expected value of the present value, \(PV\).

\hypertarget{solutions-to-tutorial-2}{%
\section{Solutions to Tutorial 2}\label{solutions-to-tutorial-2}}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  The solutions to each question are as follows:

  \begin{enumerate}
  \def\labelenumii{\arabic{enumii}.}
  \tightlist
  \item
    \((1.03)^3(1.04)^{2.5} (1.02)^{12} = 1.528611\)
  \item
    \(5000A(0.5,2.75) = 5000(1.03)(1.04)^{2.5} (1.02)^{9} = 6788.786068\)
  \item
    We first find the rate \(j\%\) per month effective that is equivalent to the rate of \(4\%\) per half-year effective.
    \[j = (1.04)^{1/6} - 1 = 0.00656.\]
    The accumulated value is \(100A(1+2/12, 3 + 7/12 ) = 100(1+j)^{10}(1.02)^{19} = 155.522118.\)
  \item
    \(25000V(0,1.5) = \frac{25000}{(1.03)^3(1.04)^{1.5}} = 21571.39968.\)
  \item
    \(8000V(0.25,2.75) = \frac{8000}{(1.03)^2(1.04)^{2.5}(1.02)^{9}} = 5720.455921.\)
  \item
    \(V(0.5,1.75) = \frac{1}{(1.03)(1.04)^{2}} = 0.897627.\)
  \end{enumerate}
\item
  The solutions to each question are as follows:

  \begin{enumerate}
  \def\labelenumii{\arabic{enumii}.}
  \tightlist
  \item
    With \(i = 7.25\%\) per time period, \(V(4) = 100 (1+i)^4 - 30(1+i)^3 - 30 (1+i)^2 + 100 (1+i) - 30 = 138.041762.\)
  \item
    \(V(8) = V(4)\cdot (1+i)^4 = 182.641597.\)
  \item
    \(PV(0) = V(4)\cdot (1+i)^{-4} = 104.332903.\)
  \end{enumerate}
\item
  The solutions to each question are as follows:

  \begin{enumerate}
  \def\labelenumii{\arabic{enumii}.}
  \tightlist
  \item
    With \$ = 6\%\$ per time period, \(V(5) = 5000 (1+i)^5 - 2000(1+i)^{3.75} - 1000 (1+i)^{2.25} + 4000 (1+i)^{1.5} - 500(1+i) = 6897.948585.\)
  \item
    \(V(2) = V(5)(1+i)^{-3} = 5791.650645.\)
  \item
    \(PV(0) = V(5)(1+i)^{-5} = 5154.548456.\)
  \end{enumerate}
\item
  The solutions to each question are as follows:

  \begin{enumerate}
  \def\labelenumii{\arabic{enumii}.}
  \tightlist
  \item
    \(V(1/1/2019) = 100(1.04)(1.03)^{3.5}(1.015)^{15} - 30 (1.03)^{3.5} (1.015)^{15}- 30 (1.03)^{1.5} (1.015)^{15} + 100 (1.015)^{12} - 30 = 152.955693.\)
  \item
    \(PV(0)= V(1/1/2015) = \frac{152.955693}{(1.04)(1.03)^{3.5}(1.015)^{15}} =106.074596.\)
  \item
    \(V(1/7/2017) = PV(0)(1.04)(1.03)^3 = 120.546998.\)
  \end{enumerate}
\end{enumerate}

\hypertarget{solutions-to-tutorial-3}{%
\section{Solutions to Tutorial 3}\label{solutions-to-tutorial-3}}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Let \(j\) be the effective rate per month equivalent to \(i = 2\)\%. We have
  \[ j = (1.02)^{1/12}  - 1= 0.001652. \]
  Hence,
\end{enumerate}

\[ PV(0) = 200 \ddot{a}^{j}_{120} + 300 \ddot{a}^{j}_{180} \left( \frac{1}{1.02} \right)^{10} = 60148.03. \]

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{1}
\item
  The solutions to each question are as follows:

  \begin{enumerate}
  \def\labelenumii{\arabic{enumii}.}
  \item
    The cashflows have been splitted into three periods: (a) from time point 0-5, (b) 5-10 and (c) time point 10 onward.
    \[PV(0) = 1000 ( a^{3\%}_{5} + 1.03^{-5} a^{4\%}_{5} +  1.03^{-5} 1.04^{-5} a^{5\%}_{5}) = 11489.49  \]
  \item
    We have
    \[PV(0) = 500 ( \ddot{a}^{3\%}_{5} + 1.03^{-5} \ddot{a}^{4\%}_{5} +  1.03^{-5} 1.04^{-5} \ddot{a}^{5\%}_{10}) = 7229.67  \]
  \item
    The accumuated value is
    \[100 (Is)^{3\%}_{5} (1.04)^5 (1.05)^{20} + \left[100 (Is)^{4\%}_{5} + 500 s^{4\%}_{5} \right] (1.05)^{20}  + \left[100 (Is)^{5\%}_{20} + 1000 s^{5\%}_{20} \right]= 78929.01  \]
  \item
    Let \(i_1 = 3\%, i_2 = 4\%\) and \(i_3 = 5\%\). The accumuated value is given by
    \[\begin{aligned} 
     V(18) &= \left[1000(1+i_1)^5 + 1000(1.02)(1+i_1)^4 + 1000(1.02)^2(1+i_1)^3 + \ldots + 1000(1.02)^4(1+i_1)\right](1.04)^5(1.05)^8   \\
     &+ \left[1000(1.02)^5(1+i_2)^5 + 1000(1.02)^6(1+i_2)^4 + 1000(1.02)^7(1+i_2)^3 + \ldots + 1000(1.02)^9(1+i_2)\right](1.05)^8   \\
     &+ \left[1000(1.02)^{10}(1+i_3)^8 + 1000(1.02)^{11}(1+i_3)^7 + 1000(1.02)^{12}(1+i_3)^6 + \ldots + 1000(1.02)^{17}(1+i_3)\right]  \\
     &= 1000(1.02)^5 \left[ \left(\frac{1+i_1}{1.02}\right)^5   + \left(\frac{1+i_1}{1.02}\right)^4 + \ldots + \left(\frac{1+i_1}{1.02}\right) \right](1.04)^5(1.05)^8 \\
     &+ 1000(1.02)^{10} \left[ \left(\frac{1+i_2}{1.02}\right)^5   + \left(\frac{1+i_2}{1.02}\right)^4 + \ldots + \left(\frac{1+i_2}{1.02}\right) \right](1.05)^8 \\
      &+ 1000(1.02)^{18} \left[ \left(\frac{1+i_3}{1.02}\right)^8   + \left(\frac{1+i_3}{1.02}\right)^7 + \ldots + \left(\frac{1+i_3}{1.02}\right) \right] 
     \end{aligned}\]
    Let \(1+j_1 = \frac{1+i_1}{1.02}\). Then, \(j_1 = 0.009804\) and
    \[ \left[ \left(\frac{1+i_1}{1.02}\right)^5   + \left(\frac{1+i_1}{1.02}\right)^4 + \ldots + \left(\frac{1+i_1}{1.02}\right) \right] = \frac{(1+j_1)^5 - 1}{j_1/(1+j_1)} = 5.148995.\]
    Let \(1+j_2 = \frac{1+i_2}{1.02}\). Then, \(j_2 = 0.019608\) and
    \[ \left[ \left(\frac{1+i_2}{1.02}\right)^5   + \left(\frac{1+i_2}{1.02}\right)^4 + \ldots + \left(\frac{1+i_2}{1.02}\right) \right] = 5.301921.\]
    Let \(1+j_3 = \frac{1+i_3}{1.02}\). Then, \(j_3 = 0.029412\) and
    \[ \left[ \left(\frac{1+i_3}{1.02}\right)^8   + \left(\frac{1+i_3}{1.02}\right)^7 + \ldots + \left(\frac{1+i_3}{1.02}\right) \right]  = 9.134790.\]
    Therefore, \(V(18) = 32814.45\).
  \item
    The present value is
  \end{enumerate}
\end{enumerate}

\[\begin{aligned}
    PV(0) &= \left( \frac{200}{(1.03)^4} + \frac{200}{(1.03)^5}\right) + 200 a^{0.04}_5 (1.03)^{-5} + 200 a^{0.05}_{3} (1.03)^{-5} (1.04)^{-5} \\
    &= 350.2192 + 768.0362 + 386.1574 = 1504.413
\end{aligned}\]

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{2}
\item
  The solutions to each question are as follows:

  \begin{enumerate}
  \def\labelenumii{\arabic{enumii}.}
  \tightlist
  \item
    \(240000 (1.04)^5 = 291996.7\)
  \item
    The interest amounts are \(0.04\times 240000 = 9600.\)
  \item
    By the Principle of Equivalence, we have
    \[ 240000 = X a^{0.04}_{5}. \]
    This gives X = 53910.51.
  \item
    Level installments are payable monthly, which follows
    \[ 240000 = Y a^{j}_{60}, \]
    where \(j = (1.04)^{1/12} - 1\). This gives Y = 4412.23.
  \end{enumerate}
\item
  The person retires in 30 years, when his salary is expected to be
  \(20000 \times (1.03)^{30} = 48545.25.\)
  The first payment will be half of this which is equal to 24272.62.
  The present value at age 60 of his pension is
  \[  24272.62 \times \ddot{a}^{0.029412}_{26} = 449717.9\] (the precise value is 449719.051954).
  Here we use \(\frac{1.05}{1.02} = 1.029412\) and the annuity is paid from the 60th to the 85th birthday inclusive so there are 26 payments made in advance.
  Therefore, the present value of this at age 30 is
  \[ 449717.9 \times (1.05)^{-10} \times (1.04)^{-20} = 126002.9. \]
  (the precise value is 126003.181173)
\end{enumerate}

\hypertarget{solutions-to-tutorial-4}{%
\section{Solutions to Tutorial 4}\label{solutions-to-tutorial-4}}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  To examine whether the cashflows are equivalent, we compare their present values.

  \begin{enumerate}
  \def\labelenumii{\alph{enumii}.}
  \item
    The present value of single payment of amount 14,802.44 at year 10 is
    \[ PV(0) =  \frac{14,802.44}{1.04^{10}} = 10000.\]
  \item
    The present value of the level annuity of 400 payable yearly in arrears for the next 10 years plus a lump sum of 10,000 is
    \[ PV(0) =  400 a^{0.04}_{10} +\frac{10000}{1.04^{10}} = 10000.\]
  \item
    The present value of the level annuity of 1,232.91 payable yearly in arrears for the next 10 years.
    \[ PV(0) =  1,232.91 a^{0.04}_{10}  = 10000.\]
  \end{enumerate}
\end{enumerate}

It follows that the values of these cashflows are the same, i.e.~equivalent.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{1}
\item
  The annual yield of this investment \(i\) is the solution of the equation of value:
  \[ f(i) = -2000(1+i)^8 +300 s^i_8 = 0. \]
  If we solve using software, we get \(i = 4.2394551%
  \). Instead of using software, you can also use linear interpolation to approximate the solution.
\item
  Working in time unit of half year, the equation of value is
  \[ f(i) = -5000(1+i)^{12 \times 2} + 300 s^i_{24} = 0. \]
  The yield \(i\) per half year is \(i = 3.1491266\%\) and hence the annual yield is \(6.397423\%.\)
\item
  The equation of value is
  \[ f(i) = -100(1+i)^{7} + 20 s^i_{3}(1+i)^{4}  + 25 s^i_{4} = 0. \]
  The annual yield is \(12.6209232\%.\)
\item
  You are suggested to draw the time line for these cashflows. The equation of value is
  \[ f(i) = -5 \ddot{s}^i_{3}(1+i)^{9}   + 4 s^i_{6} = 0. \]
  The annual yield is \(5.7285486\%.\)
\end{enumerate}

\hypertarget{solutions-to-tutorial-5}{%
\section{Solutions to Tutorial 5}\label{solutions-to-tutorial-5}}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  The monthly repayment can be calculated from this equation
  \[ X = \frac{30000}{a^j_6} = \frac{30000}{5.931847} = 5057.45,\]
  where \(j = (1.04)^{1/12} - 1 = 0.003274.\)
\end{enumerate}

The complete loan schedule is illustrated below:

\begin{longtable}[]{@{}ccccc@{}}
\toprule
Time & Repayment & Interest Content & Capital Content & Capital Outstanding \\
\midrule
\endhead
0 & - & - & - & 30000 \\
1 & \(X\) & 98.21 & 4959.23 & 25040.77 \\
2 & \(X\) & 81.98 & 4975.47 & 20065.30 \\
3 & \(X\) & 65.69 & 4991.76 & 15073.54 \\
4 & \(X\) & 49.35 & 5008.10 & 10065.44 \\
5 & \(X\) & 32.95 & 5024.50 & 5040.94 \\
6 & \(X\) & 16.50 & 5040.94 & 0 \\
\bottomrule
\end{longtable}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{1}
\tightlist
\item
  The monthly repayment can be calculated from this equation
  \[ X = \frac{800000}{a^j_{120}} = \frac{800000}{88.806749} = 9008.32,\]
  where \(j = (1.065)^{1/12} - 1 = 0.005262.\)
\end{enumerate}

The capital outstanding after 95th repayment (25 payments left) is
\[ L_{95} = 9008.32 a^j_{25} = 210506.84.  \]

Hence, the interest content of the 96th repayment is
\[ j \times L_{95} = 0.005262 \times 210506.84 = 1107.62.\]
The capital content of the 96th repayment is
\[ X - 1107.62 = 7900.70. \]

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{2}
\item
  \begin{enumerate}
  \def\labelenumii{\arabic{enumii}.}
  \tightlist
  \item
  \end{enumerate}

  \begin{enumerate}
  \def\labelenumii{\alph{enumii}.}
  \item
    \textbf{Extending the term of the loan by extra 2 year:} The original repayment is
    \[ X = \frac{100000}{a^{0.07}_{12}} = \frac{100000}{7.942686} = 12590.20,\]
    The capital outstanding after 6th repayment (6 payments left) is
    \[ L_{6} = X a^{0.07}_{6} = 60011.68.  \]
    By extending the term of the loan by extra 2 year, the revised repayment \(X'\) can be obtained (for 8 payments) from
    \[ X' = \frac{L_6}{a^{0.07}_{8}} = 10050.02\]
  \item
    \textbf{Missing the next two repayments:} From the previous result, the capital outstanding after 6th repayment \(L_6 = 60011.68\). Then in 2 years, with interest at \(7\%\) per annum, this accumulates to
    \[ L_6 \times (1.07)^2 = 68707.37. \]
    This must now be repaind by only 4 annual repayments, so the new repayment \(X''\) can be obtained from
    \[ X'' = \frac{68707.37}{a^{0.07}_{4}} = 20284.35.\]
  \end{enumerate}

  \begin{enumerate}
  \def\labelenumii{\arabic{enumii}.}
  \setcounter{enumii}{1}
  \tightlist
  \item
    The capital outstanding will accumulate (at \(10\%\)) to
    \[ L_6 \times (1.1)^2 = 72614.14. \]
  \end{enumerate}

  The new repayment amount \(X'''\) is
  \[X''' = \frac{72614.14}{a^{0.07}_{4}} = 21437.73.\]

  \begin{enumerate}
  \def\labelenumii{\arabic{enumii}.}
  \setcounter{enumii}{2}
  \tightlist
  \item
    The new repayment amount will be
    \[\frac{72614.14}{a^{0.07}_{8}} = 12160.53.\]
  \end{enumerate}
\item
  You are suggested to draw the time line for these cashflows. Let \(X\) be the level of repayment of the first 6 years (\(2X\) will be repaid after this period for the last 6 years). It can be obtained from
  \[ 50000 = X(a^{0.04}_6 + 2 a^{0.05}_6 (1.04)^{-6}) = 3769.34.\]
\item
  \begin{enumerate}
  \def\labelenumii{\arabic{enumii}.}
  \tightlist
  \item
    Let \(X\) be the first annual repayment. Then,\\
    \[ 40000 = X(v + v^2(1.02) + v^3(1.02)^2 + \ldots + v^{10}(1.02)^9),\]
    where \(v = 1/(1.065).\) By rewriting the above equation, we have
    \[ 40000 = \frac{X}{1.02}(\frac{1.02}{1.065} + \left( \frac{1.02}{1.065} \right)^2 + \left( \frac{1.02}{1.065} \right)^3 + \ldots + \left( \frac{1.02}{1.065} \right)^{10}),\]
  \end{enumerate}

  Let \(i' = \left( \frac{1.065}{1.02} -1 \right) = 0.044118.\) Hence,
  \[ 40000 = \frac{X}{1.02} \cdot a^{i'}_{10},\]
  and \(X = 5133.91.\)

  \begin{enumerate}
  \def\labelenumii{\arabic{enumii}.}
  \setcounter{enumii}{1}
  \tightlist
  \item
    We will calculate the capital outstanding after 7th repayment, \(L_7\) (3 payments left). We first find the amount \(X_8\)of the 8th repayment,
    \[X_8 = X(1.02)^7 = 5897.25.\]
  \end{enumerate}

  So the capital outstanding after the 7th repayment is equal to the present value of the remaining 3 repayments (see the table below).
\end{enumerate}

\begin{longtable}[]{@{}ccccc@{}}
\toprule
Time & 7 & 8 & 9 & 10 \\
\midrule
\endhead
Payment & \(L_7 = ?\) & \(X_8\) & \(X_8 (1.02)\) & \(X_8(1.02)^2\) \\
\bottomrule
\end{longtable}

It follows that
\[
\begin{aligned} L_7 &= X_8( v + v^2 + v^3) \\
&= \frac{X_8}{(1.02)} a^{i'}_3 \\
&= 15919.94,
\end{aligned}\]
where \(v\) and \(i'\) are the same as above.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{2}
\tightlist
\item
  The interest content of the 8th repayment is
  \[ L_7 * i = 15919.94 \times 0.065 = 1034.80.\]
\end{enumerate}

\hypertarget{tutorial-6}{%
\section{Tutorial 6}\label{tutorial-6}}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  A company issues a bond of nominal amount 10,000 with a term of 5
  years and a coupon of 6\% convertible semiannually, to be redeemed at
  110\%. Calculate the price of the bond to give a redemption yield of
  8\% pa effective to an investor who pays no tax.
\item
  A 10-year bond of nominal amount 1,000 paying a half-yearly coupon of
  10\% per annum and redeemable at par. Calculate the price of this
  bond to give a redemption yield of 7\% per annum effective after
  taxes to

  \begin{enumerate}
  \def\labelenumii{\arabic{enumii}.}
  \item
    an investor who pays no taxes.
  \item
    an investor who is subject to income tax at 15\% but no CGT.
  \item
    an investor who is subject to
    income tax at 15\% and CGT at 20\%.
  \item
    If the investor question 2.3 would like to secure a redemption yield of 9\%
    pa, calculate the price for the bond.
  \end{enumerate}
\item
  An investor who pays income tax at 20\%, but no CGT buys a 15-year
  bond to be redeemed at 105\%, bearing semi-annual coupons of 10\% pa.

  \begin{enumerate}
  \def\labelenumii{\arabic{enumii}.}
  \item
    Calculate the price per 100 THB nominal to give a yield of 9\% pa
    effective.
  \item
    Just after the 20th coupon payment, the income tax rate changes
    to 15\%. If the investor holds the bond to redemption, calculate
    the realised yield on the whole transaction.
  \end{enumerate}
\item
  A 15-bond of a nominal amount of 10,000 THB, bearing semi-annual coupons
  of 6\% pa, to be redeemed at 98\%.

  \begin{enumerate}
  \def\labelenumii{\arabic{enumii}.}
  \item
    An investor who is subject to income tax at 30\% and CGT at 20\%
    buys this bond for 9,000 THB. Calculate the net yield per annum for
    this transaction.
  \item
    If the investor wishes to obtain a net redemption yield of 7\%
    pa, calculate the price that the investor should pay for the
    bond.
  \end{enumerate}
\item
  A company issues a bond of nominal 100 THB amount with a term of 15 years
  and a coupon of 7\% convertible semiannually, to be redeemed at par.

  \begin{enumerate}
  \def\labelenumii{\arabic{enumii}.}
  \item
    Calculate the price of the bond if it is priced at issue to give
    a redemption yield of 8\% pa effective to a non-tax paying
    investor.
  \item
    Investor A liable to income tax at 25\% and capital gain tax at
    20\% bought the bond on the issue date. Just after the 15th
    coupon payment, the investor A sold the bond to Investor B. The
    investor B, subject to income tax at 30\% and capital gain tax at
    30\% paid the price that gives a net redemption yield of 6.5\%.
    Calculate the price that investor B paid.
  \item
    Calculate the realised yield for Investor A's transaction.
  \end{enumerate}
\end{enumerate}

\hypertarget{tutorial-7}{%
\section{Tutorial 7}\label{tutorial-7}}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  Consider a 5-year bond of a nominal amount of 100 THB , bearing annual
  coupons of 8\% pa, to be redeemed at 110\%. The bond was issued in
  July 2012 and its issue price was 100\%. With reference to the CPI
  given in the lecture note, show that the real yield to an investor
  who is not subject to tax is 8.82\%.
\item
  A particular transaction will provide an effective rate of interest
  of 6\% per annum. The period of the transaction is one year.

  \begin{enumerate}
  \def\labelenumii{\arabic{enumii}.}
  \item
    If the annual inflation rate over this one year period will be
    constant and equal to 2.5\%, calculate the real yield on this
    transaction.
  \item
    Calculate the constant annual rate of inflation at which the
    investor will obtain a real yield on this transaction of at
    least 4.25\% per annum.
  \item
    Calculate the real yield on this transaction if inflation will
    be 3\% pa for the first nine months of the year and then 3.25\%pa
    for the remaining three months.
  \end{enumerate}
\item
  Consider a 3-year bond of a nominal amount of 100 THB, bearing annual
  coupons of 6\% pa, to be redeemed at par. The bond was issued in 15
  January 2015 and its issue price was 95\%.

  An investor who pays no tax purchased this bond on the issue date
  and held it until redemption.

  \begin{enumerate}
  \def\labelenumii{\arabic{enumii}.}
  \item
    Show that the yield obtained by this investor is approximately
    7.94\%.
  \item
    Show that the real yield on this investment is approximately
    1.80\% assuming the CPI values are given below:

    \begin{longtable}[]{@{}rrrrr@{}}
    \toprule
    Year & 2015 & 2016 & 2017 & 2018 \\
    \midrule
    \endhead
    CPI on 15 January & 100 & 103.3 & 111.0 & 119.5 \\
    \bottomrule
    \end{longtable}
  \end{enumerate}
\item
  An investor who is not liable to tax had the choice of purchasing
  two investments made on 1 Apr 2018.

  \begin{enumerate}
  \def\labelenumii{(\Alph{enumii})}
  \item
    A 10-year bond of a nominal of 100 THB, bearing a half-yearly coupon of
    9\% per annum and redeemable at par. The issue price was at 110\%.
  \item
    A 10-year index linked bond at a price of 135 THB per 100 THB nominal, bearing a
    half-yearly coupon of 4\% per annum and redeemable at par. The
    CPI base figure for indexing is 100.24 and the CPI figure
    applicable to the next coupon (payable on 1 Oct 2018) is 145.68.
    (Here 145.68 is the CPI index on 1 Apr 2018).
  \end{enumerate}

  Assume that CPI will grow at a rate of 2.5\% per annum from its
  latest known value of 145.68 on 1 Apr 2018.

  \begin{enumerate}
  \def\labelenumii{\arabic{enumii}.}
  \item
    Calculate the real rate of return (yield) per annum earned on
    both investments A and B.
  \item
    Determine which of the two investments yielded the highest real
    rate of return per annum.
  \end{enumerate}
\item
  An investor who is not liable to tax had the choice of purchasing
  two investments made on 15 Jan 2013.

  \begin{enumerate}
  \def\labelenumii{(\Alph{enumii})}
  \item
    50,000 was placed in a 5-year term special saving account. The
    effective rate of interest was 2.5\% p.a. for the first year, 3.5
    \% p.a. for the second year, 4.5 \% p.a. for the third year, 5.5\%
    p.a. for the fourth year and 6.5\% p.a. for the fifth year.
  \item
    50,000 was used to purchase an annuity payable annually in arrears
    for 5 years to yield 6\% p.a. effective.
  \end{enumerate}

  Assume that the values of CPI are as follows:

  \begin{longtable}[]{@{}rrrrrrr@{}}
  \toprule
  Year & 2013 & 2014 & 2015 & 2016 & 2017 & 2018 \\
  \midrule
  \endhead
  CPI on 15 January & 100 & 104.17 & 110.17 & 111.08 & 112.67 & 114.83 \\
  \bottomrule
  \end{longtable}

  \begin{enumerate}
  \def\labelenumii{\arabic{enumii}.}
  \item
    Calculate the real rate of return (yield) per annum earned on
    both investments A and B.
  \item
    Determine which of the two investments yielded the highest real
    rate of return per annum.
  \end{enumerate}
\end{enumerate}

\hypertarget{tutorial-8}{%
\section{Tutorial 8}\label{tutorial-8}}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  10,000 was placed in a 3-year term special saving account on 15
  Jan 2015. The effective rate of interest was 2.5\% p.a. for the first
  year, 3.5 \% p.a. for the second year, 4.5 \% p.a. for the third year.
  Assume that the values of CPI are as follows:

  \begin{longtable}[]{@{}rrrrrll@{}}
  \toprule
  Year & 2015 & 2016 & 2017 & 2018 & & \\
  \midrule
  \endhead
  CPI on 15 January & 100 & 104.08 & 106.67 & 108.83 & & \\
  \bottomrule
  \end{longtable}

  What is the real rate of return (yield) per annum earned on this
  investment?

  \begin{enumerate}
  \def\labelenumii{\Alph{enumii}.}
  \item
    0.618\%
  \item
    0.629\%
  \item
    0.724\%
  \item
    0.762\%
  \item
    none of the above
  \end{enumerate}
\item
  \protect\hypertarget{Tutorial8-2}{}{\[Tutorial8-2\]} A company's cash position, measured in
  million of bahts, follows a generalised Wiener process with a drift
  rate of 0.25 per quarter and a variance rate of 9 per quarter. The
  initial cash position is 35. What is the expected cash position at
  the end of 6 months?

  \begin{enumerate}
  \def\labelenumii{\Alph{enumii}.}
  \item
    35.25
  \item
    35.5
  \item
    35.75
  \item
    36
  \item
    none of the above
  \end{enumerate}
\item
  \protect\hypertarget{Tutorial8-3}{}{\[Tutorial8-3\]} Suppose that data on a stock price at
  the end of 63 consecutive trading days gives the sum of the daily
  returns \[\sum_{i=1}^{62} \ln(S_i/S_{i-1}) = 0.25\] and the sum of
  the daily returns squared
  \[\sum_{i=1}^{62} \left( \ln(S_i/S_{i-1}) \right)^2= 0.0042.\]
  Assume that there are 252 trading days per year. What is the
  estimated value of the stock price volatility per annum?

  \begin{enumerate}
  \def\labelenumii{\Alph{enumii}.}
  \item
    9.28\%
  \item
    10.72\%
  \item
    11.42\%
  \item
    12.37\%
  \item
    none of the above
  \end{enumerate}
\item
  What is the standard error (per annum) of the estimate obtained in
  Question \protect\hyperlink{Tutorial8-3}{\[Tutorial8-3\]}?

  \begin{enumerate}
  \def\labelenumii{\Alph{enumii}.}
  \item
    0.72\%
  \item
    0.85\%
  \item
    0.93\%
  \item
    1.02\%
  \item
    none of the above
  \end{enumerate}
\item
  With the drift rate and the variance rate as given in the Question
  \protect\hyperlink{Tutorial8-2}{\[Tutorial8-2\]}, What is the
  company's initial cash position so that the company has a less than
  5\% chance of a negative cash position by the end of 1 year? Note
  that \(\Pr( Z \le 1.645) = 0.95\) for a standard normal random number
  \(Z\).

  \begin{enumerate}
  \def\labelenumii{\Alph{enumii}.}
  \item
    6.48
  \item
    6.84
  \item
    7.29
  \item
    7.92
  \item
    none of the above
  \end{enumerate}
\item
  Suppose that a stock price follow geometric Brownian motion with an
  initial price of 40 TBH, an expected return of 8\% per annum and a
  volatility of 30\% per annum. Using monthly time steps and the random
  samples from a normal distribution given in the table below, what is
  the simulated value of the stock price path at time 3 months?

  \begin{longtable}[]{@{}lrrrlll@{}}
  \toprule
  Period (n) & 1 & 2 & 3 & & & \\
  \midrule
  \endhead
  Random sample from \(N(0,1)\) for period \(n\) & 0.62 & 1.34 & -0.76 & & & \\
  \bottomrule
  \end{longtable}

  \begin{enumerate}
  \def\labelenumii{\Alph{enumii}.}
  \item
    45.92
  \item
    46.78
  \item
    47.40
  \item
    48.80
  \item
    none of the above
  \end{enumerate}
\item
  An investor who was not subject to tax purchased an index-linked
  bond issued on 15 January 2016 with a term of 2 years. The annual
  coupon rate was 2\% p.a. payable half-yearly in arrears and the
  redemption rate was 100\%. The coupons and redemption payments were
  adjusted with reference to the CPI value of 3 months before the
  payments were made.

  The value of the inflation index at particular dates are as follows:

  \begin{longtable}[]{@{}lrrrrrrrrrr@{}}
  \toprule
  Date & Oct 15 & Jan 16 & Apr 16 & Jul 16 & Oct 16 & Jan 17 & Apr 17 & Jul 17 & Oct 17 & Jan 18 \\
  \midrule
  \endhead
  CPI (Date) & 96 & 97 & 99 & 100 & 102 & 104 & 105 & 109 & 111 & 112 \\
  \bottomrule
  \end{longtable}

  \begin{enumerate}
  \def\labelenumii{\arabic{enumii}.}
  \item
    Write down the value of the base CPI figure.
  \item
    Calculate the actual payments per 100 THB nominal received by
    the investor. Clearly state the date on which each payment was
    received.
  \item
    Calculate the real payments per 100 THB nominal in terms of
    their purchasing power at 15 January 2016.
  \item
    Calculate the purchase price of the bond per 100 THB nominal if
    the investor obtained a \underline{\textbf{real}} redemption yield of
    0.79\% p.a. effective on the bond.
  \end{enumerate}
\item
  Consider a stock that pays no dividends, provides an expected return
  of 10\% per annum with continuous compounding and has a volatility of
  25\% per annum. Assume that the stock price follows geometric
  Brownian motion and its current stock price is 40 THB.

  \begin{enumerate}
  \def\labelenumii{\arabic{enumii}.}
  \item
    Find the probability distribution of the logarithm of the stock
    price \(S_T\) in 6 months' time.
  \item
    Calculate the mean and the standard deviation of \(\ln S_T\) in 6
    months' time.
  \item
    Find the 95\% confidence interval of \(S_T\) in 6 months' time.
  \end{enumerate}
\end{enumerate}

\end{document}
